package com.rootopathy.careos.administration.application;

import com.rootopathy.careos.administration.domain.*;
import com.rootopathy.careos.governance.application.GovernedMutationExecutor;
import com.rootopathy.careos.governance.domain.*;
import com.rootopathy.careos.tenancy.application.TenantAuthorizationOperations;
import com.rootopathy.careos.tenancy.domain.*;
import java.nio.charset.StandardCharsets;
import java.security.MessageDigest;
import java.time.*;
import java.util.*;
import java.util.regex.Pattern;
import org.springframework.stereotype.Service;
import tools.jackson.databind.ObjectMapper;

@Service
public class ConfigurationActivationService {
  private static final Pattern KEY=Pattern.compile("[A-Za-z0-9._:-]{16,128}"),DIGEST=Pattern.compile("[0-9a-f]{64}"),ETAG=Pattern.compile("\"configuration:([0-9a-fA-F-]{36}):([0-9]+)\"");
  private final TenantAuthorizationOperations auth; private final GovernedMutationExecutor mutations;
  private final ConfigurationActivationStore store; private final OrganizationAdministrationStore administration;
  private final ObjectMapper mapper; private final Clock clock;
  public ConfigurationActivationService(TenantAuthorizationOperations auth,GovernedMutationExecutor mutations,ConfigurationActivationStore store,OrganizationAdministrationStore administration,ObjectMapper mapper,Clock clock){this.auth=auth;this.mutations=mutations;this.store=store;this.administration=administration;this.mapper=mapper;this.clock=clock;}

  public ConfigurationActivationDirectory directory(Read c){return auth.execute(req(c.organizationId,c.actorId,c.correlationId,"configuration.readiness.read",null,null,null),store::directory);}
  public IdempotencyOutcome validate(Validate c){var reason=text(c.reason,"reason",10,500);key(c.idempotencyKey);if(c.requestedEffectiveAt==null)throw new IllegalArgumentException("requestedEffectiveAt is required");var summary=text(c.changeSummary,"changeSummary",2,500);var expected=c.configurationId==null?0:revision(c.ifMatch,c.configurationId);var changes=changes(c.changeItems);var requestHash=hash(c.configurationId,expected,summary,reason,c.requestedEffectiveAt,changes);return mutations.execute(req(c.organizationId,c.actorId,c.correlationId,"configuration.validation.run",reason,null,null),new IdempotencyCommand("configuration.validation.run",c.idempotencyKey,requestHash,clock.instant().plusSeconds(86400)),x->{var baseline=store.baseline(x,c.configurationId,expected);var baselineDigest=hash(baseline.canonicalState());var readiness=project(administration.readiness(x),store.candidateSatisfiedGates(x,changes));var gatesJson=json(readiness.gates());var resultDigest=hash(x.organizationId(),baseline.configurationId(),expected,baseline.parentDigest(),baseline.baselineRevision(),baselineDigest,changes,readiness.catalogueVersion(),gatesJson,readiness.evaluatedAt());var draft=new ConfigurationActivationStore.ValidationDraft(baseline.configurationId(),baseline.newConfiguration(),expected,baseline.parentVersionId(),baseline.parentDigest(),baseline.baselineRevision(),baselineDigest,summary,reason,c.requestedEffectiveAt,changes);var result=store.validate(x,draft,readiness,gatesJson,resultDigest);var payload=json(Map.of("blockerCount",result.blockerCount(),"configurationId",result.configurationId(),"expiresAt",result.expiresAt(),"resultDigest",result.resultDigest(),"resultId",result.resultId(),"warningCount",result.warningCount()));return mutation(result.directory(),201,"configuration.validation.completed",result.configurationId(),reason,payload);});}
  public IdempotencyOutcome submit(Action c){var reason=text(c.reason,"reason",10,500);key(c.idempotencyKey);var revision=revision(c.ifMatch,c.configurationId);requireResult(c.resultId,c.resultDigest);return mutations.execute(req(c.organizationId,c.actorId,c.correlationId,"configuration.submit",reason,null,null),command("configuration.submit",c,revision),x->{var result=store.submit(x,c.configurationId,revision,c.resultId,c.resultDigest);var payload=json(Map.of("configurationId",result.configurationId(),"lockVersion",result.lockVersion(),"resultDigest",result.resultDigest(),"resultId",result.resultId()));return mutation(result.directory(),200,"configuration.submitted",result.configurationId(),reason,payload);});}
  public IdempotencyOutcome approve(Decision c){return decide(c,true);} public IdempotencyOutcome reject(Decision c){return decide(c,false);}
  private IdempotencyOutcome decide(Decision c,boolean approve){var reason=text(c.reason,"reason",10,500);key(c.idempotencyKey);var revision=revision(c.ifMatch,c.configurationId);requireResult(c.resultId,c.resultDigest);var code=token(c.decisionCode,"decisionCode",80);return mutations.execute(req(c.organizationId,c.actorId,c.correlationId,"configuration.approve",reason,c.recentAuthenticationAt,c.mfaAuthenticatedAt),new IdempotencyCommand("configuration.approve",c.idempotencyKey,hash(c.configurationId,revision,c.resultId,c.resultDigest,approve,code,reason),clock.instant().plusSeconds(86400)),x->{var result=store.decide(x,c.configurationId,revision,c.resultId,c.resultDigest,approve,code,reason);var payload=json(Map.of("approvalId",result.approvalId(),"configurationId",result.configurationId(),"decisionCode",result.decisionCode(),"resultDigest",result.resultDigest()));return mutation(result.directory(),200,approve?"configuration.approved":"configuration.rejected",result.configurationId(),reason,payload);});}
  public IdempotencyOutcome activate(Activate c){var reason=text(c.reason,"reason",10,500);key(c.idempotencyKey);var revision=revision(c.ifMatch,c.configurationId);var now=clock.instant();if(c.approvalId==null||!digest(c.resultDigest)||c.effectiveFrom==null||c.effectiveFrom.isBefore(now.minusSeconds(120))||c.effectiveFrom.isAfter(now.plusSeconds(120)))throw new IllegalArgumentException("activation effective time must be due within the two-minute clock-skew window");return mutations.execute(req(c.organizationId,c.actorId,c.correlationId,"configuration.activate",reason,c.recentAuthenticationAt,c.mfaAuthenticatedAt),new IdempotencyCommand("configuration.activate",c.idempotencyKey,hash(c.configurationId,revision,c.approvalId,c.resultDigest,c.effectiveFrom,reason),clock.instant().plusSeconds(86400)),x->{var evidence=store.activationEvidence(x,c.configurationId);var current=store.baseline(x,c.configurationId,revision);if(evidence.baselineRevision()!=current.baselineRevision()||!evidence.baselineDigest().equals(hash(current.canonicalState()))||!Objects.equals(evidence.parentVersionId(),current.parentVersionId())||!Objects.equals(evidence.parentDigest(),current.parentDigest()))throw new IllegalArgumentException("configuration baseline changed after approval");var result=store.activate(x,c.configurationId,revision,c.approvalId,c.resultDigest,c.effectiveFrom);var readiness=administration.readiness(x);if(readiness.blockedGates()>0)throw new IllegalArgumentException("configuration readiness blockers remain after activation");var payload=new LinkedHashMap<String,Object>();payload.put("configurationId",result.configurationId());payload.put("previousVersionId",previous(result.directory(),result.configurationId()));payload.put("effectiveFrom",c.effectiveFrom);payload.put("resultDigest",result.resultDigest());payload.put("lockVersion",result.lockVersion());return mutation(result.directory(),200,"configuration.activated",result.configurationId(),reason,json(payload));});}

  private static List<ConfigurationActivationStore.ChangeItem> changes(List<ChangeItem> values){if(values==null||values.isEmpty()||values.size()>500)throw new IllegalArgumentException("configuration change items are required");var allowed=Map.of("facility",Set.of("activated","closed"),"organization_unit",Set.of("activated","closed"),"service_location",Set.of("activated","closed"),"operating_hours_batch",Set.of("activated"),"service_definition",Set.of("activated","retired"),"service_assignment",Set.of("activated","ended"),"identifier_scheme_version",Set.of("activated","retired"));var seen=new HashSet<String>();var result=new ArrayList<ConfigurationActivationStore.ChangeItem>();for(var value:values){if(value==null||value.subjectId==null||value.expectedRevision<0||!allowed.getOrDefault(value.subjectType,Set.of()).contains(value.changeType)||!seen.add(value.subjectType+":"+value.subjectId))throw new IllegalArgumentException("invalid configuration change item");result.add(new ConfigurationActivationStore.ChangeItem(value.subjectType,value.subjectId,value.expectedRevision,value.changeType));}result.sort(Comparator.comparing(ConfigurationActivationStore.ChangeItem::subjectType).thenComparing(item->item.subjectId().toString()));return List.copyOf(result);}
  private static AdministrationReadiness project(AdministrationReadiness readiness,Set<String> satisfied){var gates=readiness.gates().stream().map(gate->"blocked".equals(gate.outcome())&&satisfied.contains(gate.key())?new ReadinessGate(gate.key(),gate.version(),gate.label(),"complete","m1.readiness.candidate_satisfied","m1.remediation.none","Selected typed revisions satisfy this gate in the candidate projection.",List.of("candidate-change-set:selected"),gate.href()):gate).toList();int complete=(int)gates.stream().filter(gate->"complete".equals(gate.outcome())).count();int blocked=(int)gates.stream().filter(gate->"blocked".equals(gate.outcome())).count();int warning=(int)gates.stream().filter(gate->"warning".equals(gate.outcome())).count();int notApplicable=(int)gates.stream().filter(gate->"not_applicable".equals(gate.outcome())).count();return new AdministrationReadiness(readiness.organizationId(),readiness.lifecycleStatus(),readiness.catalogueVersion(),readiness.organizationRevision(),readiness.evaluatedAt(),readiness.expiresAt(),complete,blocked,warning,notApplicable,gates.size(),readiness.activeMemberships(),readiness.facilityCount(),readiness.draftFacilityCount(),gates);}
  private GovernedMutation mutation(ConfigurationActivationDirectory directory,int status,String event,UUID id,String reason,String payload){return new GovernedMutation(new IdempotentResponse(status,"application/json",json(directory)),new GovernanceEvidence(new AuditRecord(event,1,"configuration",id,reason,payload),new OutboxRecord(event,1,"configuration",id,payload)));}
  private IdempotencyCommand command(String operation,Action c,long revision){return new IdempotencyCommand(operation,c.idempotencyKey,hash(c.configurationId,revision,c.resultId,c.resultDigest,c.reason),clock.instant().plusSeconds(86400));}
  private TenantAuthorizationRequest req(UUID organization,UUID actor,String correlation,String operation,String reason,Instant recent,Instant mfa){return new TenantAuthorizationRequest(organization,new AuthenticatedActorContext(actor,"configuration-activation",correlation),new OperationKey(operation),reason,recent,mfa,null);}
  private static UUID previous(ConfigurationActivationDirectory directory,UUID current){return directory.configurations().stream().filter(item->!item.configurationId().equals(current)&&"superseded".equals(item.status())).map(ConfigurationActivationDirectory.Configuration::configurationId).findFirst().orElse(null);}
  private static void requireResult(UUID id,String value){if(id==null||!digest(value))throw new IllegalArgumentException("validation result evidence required");}
  private static boolean digest(String value){return value!=null&&DIGEST.matcher(value).matches();}
  private static long revision(String etag,UUID id){var matcher=etag==null?null:ETAG.matcher(etag);if(matcher==null||!matcher.matches()||id==null||!UUID.fromString(matcher.group(1)).equals(id))throw new IllegalArgumentException("strong configuration If-Match required");return Long.parseLong(matcher.group(2));}
  private static void key(String value){if(value==null||!KEY.matcher(value).matches())throw new IllegalArgumentException("invalid Idempotency-Key");}
  private static String text(String value,String field,int min,int max){var normalized=value==null?"":value.strip();if(normalized.length()<min||normalized.length()>max||normalized.codePoints().anyMatch(Character::isISOControl))throw new IllegalArgumentException("invalid "+field);return normalized;}
  private static String token(String value,String field,int max){var normalized=value==null?"":value.strip();if(normalized.length()<1||normalized.length()>max||!normalized.matches("[a-z][a-z0-9._:-]*"))throw new IllegalArgumentException("invalid "+field);return normalized;}
  private String json(Object value){try{return mapper.writeValueAsString(value);}catch(Exception exception){throw new IllegalStateException(exception);}}
  private static String hash(Object...values){try{return HexFormat.of().formatHex(MessageDigest.getInstance("SHA-256").digest(Arrays.deepToString(values).getBytes(StandardCharsets.UTF_8)));}catch(Exception exception){throw new IllegalStateException(exception);}}

  public record Read(UUID organizationId,UUID actorId,String correlationId){}
  public record ChangeItem(String subjectType,UUID subjectId,long expectedRevision,String changeType){}
  public record Validate(UUID organizationId,UUID actorId,String correlationId,String idempotencyKey,String ifMatch,UUID configurationId,String changeSummary,String reason,Instant requestedEffectiveAt,List<ChangeItem> changeItems){}
  public record Action(UUID organizationId,UUID actorId,String correlationId,String idempotencyKey,String ifMatch,UUID configurationId,UUID resultId,String resultDigest,String reason){}
  public record Decision(UUID organizationId,UUID actorId,String correlationId,String idempotencyKey,String ifMatch,UUID configurationId,UUID resultId,String resultDigest,String decisionCode,String reason,Instant recentAuthenticationAt,Instant mfaAuthenticatedAt){}
  public record Activate(UUID organizationId,UUID actorId,String correlationId,String idempotencyKey,String ifMatch,UUID configurationId,UUID approvalId,String resultDigest,Instant effectiveFrom,String reason,Instant recentAuthenticationAt,Instant mfaAuthenticatedAt){}
}
