package com.rootopathy.careos.administration.application;

import com.rootopathy.careos.administration.domain.OperatingHoursDirectory;
import com.rootopathy.careos.administration.domain.OperatingHoursOverview;
import com.rootopathy.careos.governance.application.GovernedMutationExecutor;
import com.rootopathy.careos.governance.domain.*;
import com.rootopathy.careos.tenancy.application.TenantAuthorizationOperations;
import com.rootopathy.careos.tenancy.domain.*;
import java.nio.charset.StandardCharsets;
import java.security.MessageDigest;
import java.time.*;
import java.time.zone.ZoneRulesException;
import java.util.*;
import java.util.regex.Pattern;
import org.springframework.stereotype.Service;
import tools.jackson.databind.ObjectMapper;

@Service public class OperatingHoursService {
 public static final String READ="network.hours.read",MANAGE="network.hours.manage"; private static final Pattern KEY=Pattern.compile("[A-Za-z0-9._:-]{16,128}"),ETAG=Pattern.compile("\"operating-hours-batch:([0-9a-fA-F-]{36}):([0-9]{1,19})\""),REASON_CODE=Pattern.compile("[a-z][a-z0-9_]*(\\.[a-z0-9_]+)+");
 private final TenantAuthorizationOperations auth;private final GovernedMutationExecutor mutations;private final OperatingHoursStore store;private final ObjectMapper mapper;private final Clock clock;
 public OperatingHoursService(TenantAuthorizationOperations a,GovernedMutationExecutor m,OperatingHoursStore s,ObjectMapper o,Clock c){auth=a;mutations=m;store=s;mapper=o;clock=c;}
 public OperatingHoursOverview overview(ReadOverview c){return auth.execute(req(c.organizationId,c.actorId,c.correlationId,READ,null),store::overview);}
 public OperatingHoursDirectory directory(Read c){target(c.targetType);return auth.execute(req(c.organizationId,c.actorId,c.correlationId,READ,null),x->store.directory(x,c.targetType,c.targetId));}
 public IdempotencyOutcome replace(Replace c){var reason=text(c.reason,"reason",10,500);key(c.idempotencyKey);target(c.targetType);ZoneId zone;try{zone=ZoneId.of(c.timezone);}catch(ZoneRulesException e){throw new IllegalArgumentException("invalid timezone");}if(c.effectiveFrom==null||c.effectiveTo!=null&&!c.effectiveTo.isAfter(c.effectiveFrom)||c.effectiveFrom.isBefore(clock.instant().minusSeconds(120)))throw new IllegalArgumentException("invalid effective range");if(c.intervals==null||c.intervals.isEmpty()||c.intervals.size()>64)throw new IllegalArgumentException("weekly intervals are required");var intervals=c.intervals.stream().map(i->{interval(i.startMinute,i.endMinute,i.endsNextDay);if(i.weekday<1||i.weekday>7)throw new IllegalArgumentException("invalid weekday");return new OperatingHoursStore.Interval(i.weekday,i.startMinute,i.endMinute,i.endsNextDay);}).toList();rejectWeeklyOverlaps(intervals);var exceptions=(c.exceptions==null?List.<ExceptionDay>of():c.exceptions).stream().map(e->{if(e.localDate==null||e.localDate.isBefore(LocalDate.now(zone)))throw new IllegalArgumentException("invalid exception date");var label=text(e.label,"exception label",1,120);if(e.reasonCode==null||!REASON_CODE.matcher(e.reasonCode).matches())throw new IllegalArgumentException("invalid exception reason code");var replacements=(e.intervals==null?List.<ExceptionInterval>of():e.intervals).stream().map(i->{interval(i.startMinute,i.endMinute,i.endsNextDay);return new OperatingHoursStore.ExceptionInterval(i.startMinute,i.endMinute,i.endsNextDay);}).toList();rejectExceptionOverlaps(replacements);if(e.closed&&!replacements.isEmpty()||!e.closed&&replacements.isEmpty())throw new IllegalArgumentException("invalid exception replacement");return new OperatingHoursStore.ExceptionDay(e.localDate,e.closed,label,e.reasonCode,replacements);}).toList();OperatingHoursDstPolicy.validate(zone,c.effectiveFrom,c.effectiveTo,intervals,exceptions);var draft=new OperatingHoursStore.Draft(c.targetType,c.targetId,c.timezone,c.effectiveFrom,c.effectiveTo,intervals,exceptions);var command=new IdempotencyCommand(MANAGE,c.idempotencyKey,hash(draft,reason),clock.instant().plusSeconds(86400));return mutations.execute(req(c.organizationId,c.actorId,c.correlationId,MANAGE,reason),command,x->mutation(x,store.create(x,draft),reason,201));}
 public IdempotencyOutcome cancel(Cancel c){var reason=text(c.reason,"reason",10,500);key(c.idempotencyKey);target(c.targetType);var revision=revision(c.ifMatch,c.batchId);var command=new IdempotencyCommand(MANAGE,c.idempotencyKey,hash(c.batchId,revision,"cancelled",reason),clock.instant().plusSeconds(86400));return mutations.execute(req(c.organizationId,c.actorId,c.correlationId,MANAGE,reason),command,x->mutation(x,store.transition(x,c.targetType,c.targetId,c.batchId,revision,"cancelled"),reason,200));}
 private GovernedMutation mutation(AuthorizedTenantContext c,OperatingHoursStore.MutationResult r,String reason,int status){var event="network.hours."+(r.toState().equals("active")?"activated":r.toState());var payload=json(Map.of("batchId",r.batchId(),"targetType",r.directory().targetType(),"targetId",r.directory().targetId(),"fromState",r.fromState(),"toState",r.toState(),"effectiveFrom",r.effectiveFrom().toString()));return new GovernedMutation(new IdempotentResponse(status,"application/json",json(r.directory())),new GovernanceEvidence(new AuditRecord(event,1,"operating_hours_batch",r.batchId(),reason,payload),new OutboxRecord(event,1,"operating_hours_batch",r.batchId(),payload)));}
 private static void rejectWeeklyOverlaps(List<OperatingHoursStore.Interval> values){var ranges=values.stream().map(i->new Range((i.weekday()-1)*1440+i.startMinute(),(i.weekday()-1)*1440+i.endMinute()+(i.endsNextDay()?1440:0))).toList();rejectOverlaps(ranges,10080);}
 private static void rejectExceptionOverlaps(List<OperatingHoursStore.ExceptionInterval> values){var ranges=values.stream().map(i->new Range(i.startMinute(),i.endMinute()+(i.endsNextDay()?1440:0))).toList();rejectOverlaps(ranges,1440);}
 private static void rejectOverlaps(List<Range> ranges,int cycle){for(var i=0;i<ranges.size();i++)for(var j=i+1;j<ranges.size();j++)for(var shift=-cycle;shift<=cycle;shift+=cycle)if(ranges.get(i).start()<ranges.get(j).end()+shift&&ranges.get(j).start()+shift<ranges.get(i).end())throw new IllegalArgumentException("operating-hours intervals overlap");}
 private record Range(int start,int end){}
 private TenantAuthorizationRequest req(UUID o,UUID a,String corr,String op,String reason){return new TenantAuthorizationRequest(o,new AuthenticatedActorContext(a,"operating-hours-administration",corr),new OperationKey(op),reason,null,null,null);}private static void target(String t){if(!Set.of("facility","location").contains(t))throw new IllegalArgumentException("invalid hours target type");}private static void interval(int s,int e,boolean next){if(s<0||s>1439||e<0||e>1439||(next?e>s:e<=s))throw new IllegalArgumentException("invalid hours interval");}private static String text(String v,String f,int min,int max){var n=v==null?"":v.strip();if(n.length()<min||n.length()>max||n.codePoints().anyMatch(Character::isISOControl))throw new IllegalArgumentException("invalid "+f);return n;}private static void key(String k){if(k==null||!KEY.matcher(k).matches())throw new IllegalArgumentException("invalid Idempotency-Key");}private static long revision(String e,UUID id){var m=e==null?null:ETAG.matcher(e);if(m==null||!m.matches()||!UUID.fromString(m.group(1)).equals(id))throw new IllegalArgumentException("strong operating-hours If-Match required");return Long.parseLong(m.group(2));}private String json(Object v){try{return mapper.writeValueAsString(v);}catch(Exception e){throw new IllegalStateException(e);}}private static String hash(Object...v){try{return HexFormat.of().formatHex(MessageDigest.getInstance("SHA-256").digest(Arrays.toString(v).getBytes(StandardCharsets.UTF_8)));}catch(Exception e){throw new IllegalStateException(e);}}
 public record Read(UUID organizationId,UUID actorId,String correlationId,String targetType,UUID targetId){}
 public record ReadOverview(UUID organizationId,UUID actorId,String correlationId){}public record Replace(UUID organizationId,UUID actorId,String correlationId,String idempotencyKey,String targetType,UUID targetId,String timezone,Instant effectiveFrom,Instant effectiveTo,List<Interval> intervals,List<ExceptionDay> exceptions,String reason){}public record Cancel(UUID organizationId,UUID actorId,String correlationId,String idempotencyKey,String ifMatch,String targetType,UUID targetId,UUID batchId,String reason){}public record Interval(int weekday,int startMinute,int endMinute,boolean endsNextDay){}public record ExceptionDay(LocalDate localDate,boolean closed,String label,String reasonCode,List<ExceptionInterval> intervals){}public record ExceptionInterval(int startMinute,int endMinute,boolean endsNextDay){}
}
