package com.rootopathy.careos.administration.application;

import com.rootopathy.careos.administration.domain.ServiceAssignmentDirectory;
import com.rootopathy.careos.governance.application.GovernedMutationExecutor;
import com.rootopathy.careos.governance.domain.*;
import com.rootopathy.careos.tenancy.application.TenantAuthorizationOperations;
import com.rootopathy.careos.tenancy.domain.*;
import java.nio.charset.StandardCharsets;
import java.security.MessageDigest;
import java.time.*;
import java.util.*;
import java.util.regex.Pattern;
import org.springframework.stereotype.Service;
import tools.jackson.databind.ObjectMapper;

@Service
public class ServiceAssignmentService {
  public static final String READ="service.assignment.read", MANAGE="service.assignment.manage", LIFECYCLE="service.assignment.lifecycle";
  private static final Pattern KEY=Pattern.compile("[A-Za-z0-9._:-]{16,128}"), ETAG=Pattern.compile("\"service-assignment:([0-9a-fA-F-]{36}):([0-9]{1,19})\"");
  private static final Set<String> PREREQUISITES=Set.of("appointment_required","referral_required","authorization_required","age_restriction","accessibility_review");
  private final TenantAuthorizationOperations auth; private final GovernedMutationExecutor mutations; private final ServiceAssignmentStore store; private final ObjectMapper mapper; private final Clock clock;
  public ServiceAssignmentService(TenantAuthorizationOperations a, GovernedMutationExecutor m, ServiceAssignmentStore s, ObjectMapper o, Clock c){auth=a;mutations=m;store=s;mapper=o;clock=c;}
  public ServiceAssignmentDirectory directory(Read c){return auth.execute(req(c.organizationId,c.actorId,c.correlationId,READ,null,null,null),store::directory);}
  public IdempotencyOutcome create(Write c){return write(c,null);} public IdempotencyOutcome update(Write c){return write(c,revision(c.ifMatch,c.assignmentId));}
  private IdempotencyOutcome write(Write c,Long revision){var reason=text(c.reason,"reason",10,500);key(c.idempotencyKey);Objects.requireNonNull(c.serviceId);Objects.requireNonNull(c.facilityId);Objects.requireNonNull(c.effectiveFrom);if(c.effectiveTo!=null&&!c.effectiveTo.isAfter(c.effectiveFrom))throw new IllegalArgumentException("effectiveTo must follow effectiveFrom");if(c.capacity!=null&&(c.capacity<1||c.capacity>100000))throw new IllegalArgumentException("invalid capacity");var prerequisites=c.prerequisites==null?List.<String>of():c.prerequisites.stream().distinct().sorted().toList();if(prerequisites.size()>32||!PREREQUISITES.containsAll(prerequisites))throw new IllegalArgumentException("invalid prerequisites");var d=new ServiceAssignmentStore.Draft(c.serviceId,c.facilityId,c.locationId,c.capacity,optional(c.availabilityNotes,500),prerequisites,c.effectiveFrom,c.effectiveTo);var command=new IdempotencyCommand(MANAGE,c.idempotencyKey,hash(c.assignmentId,revision,d,reason),clock.instant().plusSeconds(86400));return mutations.execute(req(c.organizationId,c.actorId,c.correlationId,MANAGE,reason,null,null),command,x->{var r=revision==null?store.create(x,d):store.update(x,c.assignmentId,revision,d);return mutation(r,"scheduled",reason,revision==null?201:200);});}
  public IdempotencyOutcome activate(Lifecycle c){return transition(c,"scheduled","active","activated");} public IdempotencyOutcome suspend(Lifecycle c){return transition(c,"active","suspended","suspended");} public IdempotencyOutcome end(Lifecycle c){return transition(c,c.fromState,"ended","ended");} public IdempotencyOutcome cancel(Lifecycle c){return transition(c,"scheduled","cancelled","cancelled");}
  private IdempotencyOutcome transition(Lifecycle c,String from,String to,String change){if(!Set.of("scheduled","active","suspended").contains(from))throw new IllegalArgumentException("invalid source state");var reason=text(c.reason,"reason",10,500);key(c.idempotencyKey);var rev=revision(c.ifMatch,c.assignmentId);var command=new IdempotencyCommand(LIFECYCLE,c.idempotencyKey,hash(c.assignmentId,rev,from,to,reason),clock.instant().plusSeconds(86400));return mutations.execute(req(c.organizationId,c.actorId,c.correlationId,LIFECYCLE,reason,c.recentAuthenticationAt,c.mfaAuthenticatedAt),command,x->mutation(store.transition(x,c.assignmentId,rev,from,to),change,reason,200));}
  private GovernedMutation mutation(ServiceAssignmentStore.Result r,String change,String reason,int status){var event="service.assignment."+change;var payload=json(Map.of("assignmentId",r.assignmentId(),"effectiveFrom",r.effectiveFrom(),"fromState",r.fromState(),"serviceId",r.serviceId(),"targetId",r.targetId(),"toState",r.toState()));return new GovernedMutation(new IdempotentResponse(status,"application/json",json(r.directory())),new GovernanceEvidence(new AuditRecord(event,1,"service_assignment",r.assignmentId(),reason,payload),new OutboxRecord(event,1,"service_assignment",r.assignmentId(),payload)));}
  private TenantAuthorizationRequest req(UUID o,UUID a,String corr,String op,String reason,Instant recent,Instant mfa){return new TenantAuthorizationRequest(o,new AuthenticatedActorContext(a,"service-assignment-administration",corr),new OperationKey(op),reason,recent,mfa,null);} private static String text(String v,String f,int min,int max){var n=v==null?"":v.strip();if(n.length()<min||n.length()>max||n.codePoints().anyMatch(Character::isISOControl))throw new IllegalArgumentException("invalid "+f);return n;} private static String optional(String v,int max){return v==null||v.isBlank()?null:text(v,"optional field",1,max);} private static void key(String k){if(k==null||!KEY.matcher(k).matches())throw new IllegalArgumentException("invalid Idempotency-Key");} private static long revision(String e,UUID id){var m=e==null?null:ETAG.matcher(e);if(m==null||!m.matches()||id==null||!UUID.fromString(m.group(1)).equals(id))throw new IllegalArgumentException("strong assignment If-Match required");return Long.parseLong(m.group(2));} private String json(Object v){try{return mapper.writeValueAsString(v);}catch(Exception e){throw new IllegalStateException(e);}} private static String hash(Object...v){try{return HexFormat.of().formatHex(MessageDigest.getInstance("SHA-256").digest(Arrays.toString(v).getBytes(StandardCharsets.UTF_8)));}catch(Exception e){throw new IllegalStateException(e);}}
  public record Read(UUID organizationId,UUID actorId,String correlationId){} public record Write(UUID organizationId,UUID actorId,String correlationId,String idempotencyKey,String ifMatch,UUID assignmentId,UUID serviceId,UUID facilityId,UUID locationId,Integer capacity,String availabilityNotes,List<String> prerequisites,Instant effectiveFrom,Instant effectiveTo,String reason){} public record Lifecycle(UUID organizationId,UUID actorId,String correlationId,String idempotencyKey,String ifMatch,UUID assignmentId,String fromState,String reason,Instant recentAuthenticationAt,Instant mfaAuthenticatedAt){}
}
