import type { CareOsApiClient } from '../../api/client';

export type AdministrationClient = Pick<
  CareOsApiClient,
  | 'approveOrganizationMembershipChange'
  | 'approveOrganizationOwnerTransfer'
  | 'createOrganizationAddress'
  | 'createOrganizationContact'
  | 'createOrganizationIdentifier'
  | 'createOrganizationGovernanceResponsibility'
  | 'createFacilityDraft'
  | 'updateFacilityDraft'
  | 'endOrganizationAddress'
  | 'endOrganizationContact'
  | 'executeOrganizationMembershipChange'
  | 'executeOrganizationOwnerTransfer'
  | 'getAdministrationReadiness'
  | 'getOrganizationProfile'
  | 'getOrganizationInternationalSettings'
  | 'getOrganizationGovernanceDirectory'
  | 'getFacilityDirectory'
  | 'listOrganizationIdentifiers'
  | 'listOrganizationContacts'
  | 'listOrganizationMemberships'
  | 'requestOrganizationMembershipChange'
  | 'requestOrganizationOwnerTransfer'
  | 'scheduleOrganizationInternationalSettings'
  | 'supersedeOrganizationGovernanceResponsibility'
  | 'endOrganizationGovernanceResponsibility'
  | 'revokeOrganizationIdentifier'
  | 'supersedeOrganizationIdentifier'
  | 'supersedeOrganizationAddress'
  | 'supersedeOrganizationContact'
  | 'updateOrganizationIdentifier'
  | 'updateOrganizationProfile'
  | 'verifyOrganizationIdentifier'
  | 'verifyOrganizationContact'
>;
