CREATE TABLE identifier_schemes (
 id uuid PRIMARY KEY DEFAULT uuidv7(), organization_id uuid NOT NULL REFERENCES organizations(id),
 scheme_key varchar(40) NOT NULL, scope_type varchar(24) NOT NULL, scope_id uuid, description varchar(500),
 status varchar(24) NOT NULL DEFAULT 'draft', lock_version bigint NOT NULL DEFAULT 0,
 created_at timestamptz NOT NULL DEFAULT clock_timestamp(), created_by uuid NOT NULL REFERENCES users(id),
 updated_at timestamptz NOT NULL DEFAULT clock_timestamp(), updated_by uuid NOT NULL REFERENCES users(id),
 UNIQUE(organization_id,id), UNIQUE(organization_id,scheme_key),
 CHECK(scheme_key~'^[A-Z][A-Z0-9_.-]{1,39}$'), CHECK(scope_type IN ('organization','facility','service')),
 CHECK((scope_type='organization' AND scope_id IS NULL) OR (scope_type<>'organization' AND scope_id IS NOT NULL)),
 CHECK(description IS NULL OR (description=btrim(description) AND char_length(description) BETWEEN 1 AND 500 AND description !~ '[[:cntrl:]<>]')),
 CHECK(status IN ('draft','active','retired')), CHECK(lock_version>=0)
);
CREATE TABLE identifier_scheme_versions (
 id uuid PRIMARY KEY DEFAULT uuidv7(), organization_id uuid NOT NULL REFERENCES organizations(id), scheme_id uuid NOT NULL,
 version_number integer NOT NULL, prefix varchar(20) NOT NULL DEFAULT '', pattern varchar(200) NOT NULL,
 alphabet varchar(80) NOT NULL, check_digit_algorithm varchar(40), sequence_start bigint NOT NULL,
 sequence_increment integer NOT NULL, padding integer NOT NULL, preview_samples varchar(120)[] NOT NULL,
 effective_from timestamptz NOT NULL, status varchar(24) NOT NULL DEFAULT 'draft', next_sequence bigint NOT NULL,
 lock_version bigint NOT NULL DEFAULT 0, created_at timestamptz NOT NULL DEFAULT clock_timestamp(), created_by uuid NOT NULL REFERENCES users(id),
 activated_at timestamptz, activated_by uuid REFERENCES users(id), retired_at timestamptz, retired_by uuid REFERENCES users(id),
 UNIQUE(organization_id,id), UNIQUE(organization_id,scheme_id,version_number),
 FOREIGN KEY(organization_id,scheme_id) REFERENCES identifier_schemes(organization_id,id),
 CHECK(version_number>0), CHECK(prefix=btrim(prefix) AND char_length(prefix)<=20 AND prefix !~ '[[:cntrl:]<>]'),
 CHECK(char_length(pattern) BETWEEN 1 AND 200 AND pattern~'^[A-Za-z0-9\\[\\]{}()^$.*+?_|\\-]+$'),
 CHECK(alphabet~'^[A-Za-z0-9]+$' AND char_length(alphabet) BETWEEN 2 AND 80),
 CHECK(check_digit_algorithm IS NULL OR check_digit_algorithm IN ('luhn_mod_n','mod_11')),
 CHECK(sequence_start>=0 AND sequence_increment BETWEEN 1 AND 1000000 AND padding BETWEEN 1 AND 20),
 CHECK(cardinality(preview_samples) BETWEEN 1 AND 10 AND status IN ('draft','active','retired')), CHECK(next_sequence>=sequence_start), CHECK(lock_version>=0)
);
CREATE UNIQUE INDEX identifier_scheme_one_active_idx ON identifier_scheme_versions(organization_id,scheme_id) WHERE status='active';
CREATE TABLE issued_identifiers (
 id uuid PRIMARY KEY DEFAULT uuidv7(), organization_id uuid NOT NULL REFERENCES organizations(id), scheme_id uuid NOT NULL, version_id uuid NOT NULL,
 subject_type varchar(40) NOT NULL, subject_id uuid NOT NULL, identifier_value varchar(200) NOT NULL, sequence_value bigint NOT NULL,
 issued_at timestamptz NOT NULL DEFAULT clock_timestamp(), issued_by uuid NOT NULL REFERENCES users(id),
 UNIQUE(organization_id,id), UNIQUE(organization_id,scheme_id,identifier_value), UNIQUE(organization_id,scheme_id,subject_type,subject_id),
 FOREIGN KEY(organization_id,scheme_id) REFERENCES identifier_schemes(organization_id,id), FOREIGN KEY(organization_id,version_id) REFERENCES identifier_scheme_versions(organization_id,id),
 CHECK(subject_type~'^[a-z][a-z0-9_]{1,39}$')
);
ALTER TABLE identifier_schemes ENABLE ROW LEVEL SECURITY; ALTER TABLE identifier_schemes FORCE ROW LEVEL SECURITY;
ALTER TABLE identifier_scheme_versions ENABLE ROW LEVEL SECURITY; ALTER TABLE identifier_scheme_versions FORCE ROW LEVEL SECURITY;
ALTER TABLE issued_identifiers ENABLE ROW LEVEL SECURITY; ALTER TABLE issued_identifiers FORCE ROW LEVEL SECURITY;
CREATE POLICY identifier_schemes_tenant ON identifier_schemes USING(organization_id=nullif(current_setting('app.current_organization_id',true),'')::uuid) WITH CHECK(organization_id=nullif(current_setting('app.current_organization_id',true),'')::uuid);
CREATE POLICY identifier_scheme_versions_tenant ON identifier_scheme_versions USING(organization_id=nullif(current_setting('app.current_organization_id',true),'')::uuid) WITH CHECK(organization_id=nullif(current_setting('app.current_organization_id',true),'')::uuid);
CREATE POLICY issued_identifiers_tenant ON issued_identifiers USING(organization_id=nullif(current_setting('app.current_organization_id',true),'')::uuid) WITH CHECK(organization_id=nullif(current_setting('app.current_organization_id',true),'')::uuid);
CREATE FUNCTION careos_validate_identifier_scheme() RETURNS trigger LANGUAGE plpgsql AS $$ DECLARE op text:=nullif(current_setting('app.current_operation_key',true),''); actor uuid:=nullif(current_setting('app.current_actor_id',true),'')::uuid; tenant uuid:=nullif(current_setting('app.current_organization_id',true),'')::uuid; BEGIN IF current_user<>'${applicationRole}' THEN RETURN NEW; END IF; IF NEW.organization_id IS DISTINCT FROM tenant OR actor IS NULL OR op NOT IN ('identifier.scheme.manage','identifier.scheme.activate','identifier.scheme.retire') OR NEW.updated_by IS DISTINCT FROM actor OR char_length(coalesce(nullif(current_setting('app.current_authorization_reason',true),''),'')) NOT BETWEEN 10 AND 500 THEN RAISE EXCEPTION 'invalid scheme governance context' USING ERRCODE='42501'; END IF; IF TG_OP='INSERT' AND (op<>'identifier.scheme.manage' OR NEW.status<>'draft' OR NEW.created_by<>actor) THEN RAISE EXCEPTION 'schemes begin draft' USING ERRCODE='23514'; END IF; IF TG_OP='UPDATE' AND (NEW.id<>OLD.id OR NEW.organization_id<>OLD.organization_id OR NEW.scheme_key<>OLD.scheme_key OR NEW.scope_type<>OLD.scope_type OR NEW.scope_id IS DISTINCT FROM OLD.scope_id OR NEW.created_at<>OLD.created_at OR NEW.created_by<>OLD.created_by OR NEW.lock_version<>OLD.lock_version+1) THEN RAISE EXCEPTION 'invalid scheme revision' USING ERRCODE='23514'; END IF; IF TG_OP='UPDATE' AND NOT ((op='identifier.scheme.manage' AND OLD.status='draft' AND NEW.status='draft') OR (op='identifier.scheme.activate' AND OLD.status='draft' AND NEW.status='active') OR (op='identifier.scheme.retire' AND OLD.status='active' AND NEW.status='retired')) THEN RAISE EXCEPTION 'invalid scheme transition' USING ERRCODE='23514'; END IF; RETURN NEW; END $$;
CREATE TRIGGER identifier_schemes_validate BEFORE INSERT OR UPDATE ON identifier_schemes FOR EACH ROW EXECUTE FUNCTION careos_validate_identifier_scheme();
CREATE FUNCTION careos_validate_identifier_scheme_version() RETURNS trigger LANGUAGE plpgsql AS $$ DECLARE op text:=nullif(current_setting('app.current_operation_key',true),''); actor uuid:=nullif(current_setting('app.current_actor_id',true),'')::uuid; tenant uuid:=nullif(current_setting('app.current_organization_id',true),'')::uuid; BEGIN IF current_user<>'${applicationRole}' THEN RETURN NEW; END IF; IF NEW.organization_id IS DISTINCT FROM tenant OR actor IS NULL OR op NOT IN ('identifier.scheme.version.create','identifier.scheme.activate','identifier.scheme.retire') THEN RAISE EXCEPTION 'invalid scheme-version governance context' USING ERRCODE='42501'; END IF; IF TG_OP='INSERT' AND (op<>'identifier.scheme.version.create' OR NEW.status<>'draft' OR NEW.created_by<>actor OR NEW.next_sequence<>NEW.sequence_start) THEN RAISE EXCEPTION 'invalid scheme version creation' USING ERRCODE='23514'; END IF; IF TG_OP='UPDATE' AND op NOT IN ('identifier.scheme.activate','identifier.scheme.retire') THEN RAISE EXCEPTION 'scheme versions are immutable' USING ERRCODE='23514'; END IF; IF TG_OP='UPDATE' AND (NEW.id<>OLD.id OR NEW.organization_id<>OLD.organization_id OR NEW.scheme_id<>OLD.scheme_id OR NEW.version_number<>OLD.version_number OR NEW.prefix<>OLD.prefix OR NEW.pattern<>OLD.pattern OR NEW.alphabet<>OLD.alphabet OR NEW.check_digit_algorithm IS DISTINCT FROM OLD.check_digit_algorithm OR NEW.sequence_start<>OLD.sequence_start OR NEW.sequence_increment<>OLD.sequence_increment OR NEW.padding<>OLD.padding OR NEW.preview_samples<>OLD.preview_samples OR NEW.effective_from<>OLD.effective_from OR NEW.next_sequence<>OLD.next_sequence OR NEW.created_at<>OLD.created_at OR NEW.created_by<>OLD.created_by OR NEW.lock_version<>OLD.lock_version+1) THEN RAISE EXCEPTION 'scheme version content is immutable' USING ERRCODE='23514'; END IF; IF TG_OP='UPDATE' AND NOT ((op='identifier.scheme.activate' AND OLD.status='draft' AND NEW.status='active' AND NEW.activated_by=actor AND NEW.activated_at IS NOT NULL) OR (op='identifier.scheme.retire' AND OLD.status='active' AND NEW.status='retired' AND NEW.retired_by=actor AND NEW.retired_at IS NOT NULL)) THEN RAISE EXCEPTION 'invalid scheme-version transition' USING ERRCODE='23514'; END IF; RETURN NEW; END $$;
CREATE TRIGGER identifier_scheme_versions_validate BEFORE INSERT OR UPDATE ON identifier_scheme_versions FOR EACH ROW EXECUTE FUNCTION careos_validate_identifier_scheme_version();
INSERT INTO audit_event_definitions(event_name,schema_version,display_name,description,subject_type,reason_required,required_payload_keys,allowed_payload_keys,payload_schema,status,registry_version) SELECT name,1,'Identifier scheme changed','A governed identifier scheme changed.','identifier_scheme',true,ARRAY['effectiveFrom','fromState','schemeId','toState','versionId'],ARRAY['effectiveFrom','fromState','schemeId','toState','versionId'],'{"type":"object"}'::jsonb,'active','m1-candidate-1' FROM unnest(ARRAY['identifier.scheme.created','identifier.scheme.activated','identifier.scheme.retired']) name;
INSERT INTO outbox_event_definitions(event_name,schema_version,description,aggregate_type,required_payload_keys,allowed_payload_keys,payload_schema,status,registry_version) SELECT name,1,'A governed identifier scheme changed.','identifier_scheme',ARRAY['effectiveFrom','fromState','schemeId','toState','versionId'],ARRAY['effectiveFrom','fromState','schemeId','toState','versionId'],'{"type":"object"}'::jsonb,'active','m1-candidate-1' FROM unnest(ARRAY['identifier.scheme.created','identifier.scheme.activated','identifier.scheme.retired']) name;
INSERT INTO authorization_operations(operation_key,permission_key,display_name,description,mutation,denial_mode,reason_required,recent_authentication_required,recent_authentication_max_age_seconds,maximum_future_skew_seconds,maker_checker_required,status,registry_version,mfa_required) VALUES
('identifier.scheme.read','identifier.scheme.read','Read identifier schemes','Read scheme definitions and versions.',false,'hidden',false,false,NULL,NULL,false,'active','m1-candidate-1',false),
('identifier.scheme.manage','identifier.scheme.manage','Manage identifier schemes','Create and edit draft scheme definitions.',true,'explicit',true,false,NULL,NULL,false,'active','m1-candidate-1',false),
('identifier.scheme.version.create','identifier.scheme.manage','Create identifier scheme version','Create immutable draft scheme versions.',true,'explicit',true,false,NULL,NULL,false,'active','m1-candidate-1',false),
('identifier.scheme.activate','identifier.scheme.activate','Activate identifier scheme','Activate an immutable scheme version.',true,'explicit',true,true,300,5,true,'active','m1-candidate-1',true),
('identifier.scheme.retire','identifier.scheme.retire','Retire identifier scheme','Retire an active scheme version.',true,'explicit',true,true,300,5,true,'active','m1-candidate-1',true);
INSERT INTO authorization_operation_events(operation_key,event_kind,event_name,schema_version,status,registry_version) SELECT CASE name WHEN 'identifier.scheme.created' THEN 'identifier.scheme.manage' WHEN 'identifier.scheme.activated' THEN 'identifier.scheme.activate' ELSE 'identifier.scheme.retire' END,kind,name,1,'active','m1-candidate-1' FROM unnest(ARRAY['audit','outbox']) kind CROSS JOIN unnest(ARRAY['identifier.scheme.created','identifier.scheme.activated','identifier.scheme.retired']) name;
REVOKE ALL ON identifier_schemes,identifier_scheme_versions,issued_identifiers FROM PUBLIC; GRANT SELECT,INSERT,UPDATE ON identifier_schemes,identifier_scheme_versions TO "${applicationRole}"; GRANT SELECT,INSERT ON issued_identifiers TO "${applicationRole}";
