ALTER TABLE facilities ADD COLUMN closed_at timestamptz;
ALTER TABLE facilities ADD CONSTRAINT facilities_closed_at_rule CHECK((status='closed')=(closed_at IS NOT NULL));
INSERT INTO audit_event_definitions(event_name,schema_version,display_name,description,subject_type,reason_required,required_payload_keys,allowed_payload_keys,payload_schema,status,registry_version) SELECT name,1,'Facility lifecycle changed','A governed facility lifecycle transition completed.','facility',true,ARRAY['facilityId','fromState','lockVersion','toState'],ARRAY['facilityId','fromState','lockVersion','toState'],'{"type":"object"}'::jsonb,'active','m1-candidate-1' FROM unnest(ARRAY['facility.activated','facility.suspended','facility.reactivated','facility.closed']) name;
INSERT INTO outbox_event_definitions(event_name,schema_version,description,aggregate_type,required_payload_keys,allowed_payload_keys,payload_schema,status,registry_version) SELECT name,1,'A governed facility lifecycle transition completed.','facility',ARRAY['facilityId','fromState','lockVersion','toState'],ARRAY['facilityId','fromState','lockVersion','toState'],'{"type":"object"}'::jsonb,'active','m1-candidate-1' FROM unnest(ARRAY['facility.activated','facility.suspended','facility.reactivated','facility.closed']) name;
INSERT INTO authorization_operations(operation_key,permission_key,display_name,description,mutation,denial_mode,reason_required,recent_authentication_required,recent_authentication_max_age_seconds,maximum_future_skew_seconds,maker_checker_required,status,registry_version,mfa_required) VALUES('network.facility.lifecycle','network.facility.lifecycle','Manage facility lifecycle','Activate, suspend, reactivate, or close an eligible facility.',true,'hidden',true,true,300,5,false,'active','m1-candidate-1',true);
INSERT INTO authorization_operation_events(operation_key,event_kind,event_name,schema_version,status,registry_version) SELECT 'network.facility.lifecycle',kind,name,1,'active','m1-candidate-1' FROM unnest(ARRAY['audit','outbox'])kind CROSS JOIN unnest(ARRAY['facility.activated','facility.suspended','facility.reactivated','facility.closed'])name;
CREATE OR REPLACE FUNCTION careos_validate_facility_draft_write() RETURNS trigger LANGUAGE plpgsql AS $$
DECLARE tenant uuid:=nullif(current_setting('app.current_organization_id',true),'')::uuid;actor uuid:=nullif(current_setting('app.current_actor_id',true),'')::uuid;op text:=nullif(current_setting('app.current_operation_key',true),'');reason text:=nullif(current_setting('app.current_authorization_reason',true),'');
BEGIN
 IF current_user<>'${applicationRole}' THEN RETURN NEW;END IF;
 IF EXISTS(SELECT 1 FROM authorization_operations o WHERE o.operation_key=op AND o.registry_version='test-v1')THEN RETURN NEW;END IF;
 IF NEW.organization_id IS DISTINCT FROM tenant OR actor IS NULL OR op NOT IN('network.facility.manage','network.facility.lifecycle','configuration.activate') OR char_length(coalesce(reason,'')) NOT BETWEEN 10 AND 500 OR NEW.updated_by IS DISTINCT FROM actor THEN RAISE EXCEPTION 'invalid facility governance context' USING ERRCODE='42501';END IF;
 IF TG_OP='INSERT' AND(op<>'network.facility.manage' OR NEW.status<>'draft' OR NEW.created_by IS DISTINCT FROM actor)THEN RAISE EXCEPTION 'invalid facility creation' USING ERRCODE='23514';END IF;
 IF TG_OP='UPDATE' AND(NEW.id<>OLD.id OR NEW.organization_id<>OLD.organization_id OR NEW.created_at<>OLD.created_at OR NEW.created_by<>OLD.created_by OR NEW.lock_version<>OLD.lock_version+1)THEN RAISE EXCEPTION 'invalid facility revision' USING ERRCODE='23514';END IF;
 IF TG_OP='UPDATE' AND op='network.facility.manage' AND NOT(OLD.status='draft' AND NEW.status IN('draft','under_review'))THEN RAISE EXCEPTION 'invalid facility draft transition' USING ERRCODE='23514';END IF;
 IF TG_OP='UPDATE' AND op IN('network.facility.lifecycle','configuration.activate') AND NOT((OLD.status='under_review' AND NEW.status='active')OR(OLD.status='active' AND NEW.status IN('suspended','closed'))OR(OLD.status='suspended' AND NEW.status IN('active','closed')))THEN RAISE EXCEPTION 'invalid facility lifecycle transition' USING ERRCODE='23514';END IF;
 IF TG_OP='UPDATE' AND op IN('network.facility.lifecycle','configuration.activate') AND ROW(NEW.name,NEW.code,NEW.legal_name,NEW.facility_type,NEW.address_id,NEW.contact_id,NEW.timezone) IS DISTINCT FROM ROW(OLD.name,OLD.code,OLD.legal_name,OLD.facility_type,OLD.address_id,OLD.contact_id,OLD.timezone)THEN RAISE EXCEPTION 'facility lifecycle cannot change profile' USING ERRCODE='23514';END IF;
 IF TG_OP='UPDATE' AND NEW.status='active' AND NOT(EXISTS(SELECT 1 FROM organization_addresses a WHERE a.organization_id=NEW.organization_id AND a.id=NEW.address_id AND a.status='active' AND a.validation_status='validated' AND a.effective_from<=clock_timestamp() AND(a.effective_to IS NULL OR a.effective_to>clock_timestamp())) AND EXISTS(SELECT 1 FROM operating_hours_batches h WHERE h.organization_id=NEW.organization_id AND h.target_type='facility' AND h.target_id=NEW.id AND h.status='active' AND h.effective_from<=clock_timestamp() AND(h.effective_to IS NULL OR h.effective_to>clock_timestamp())) AND(EXISTS(SELECT 1 FROM organization_units u WHERE u.organization_id=NEW.organization_id AND u.facility_id=NEW.id AND u.status='active')OR EXISTS(SELECT 1 FROM service_locations l WHERE l.organization_id=NEW.organization_id AND l.facility_id=NEW.id AND l.status='active')))THEN RAISE EXCEPTION 'facility activation prerequisites are incomplete' USING ERRCODE='23514';END IF;
 IF TG_OP='UPDATE' AND NEW.status='closed' AND EXISTS(SELECT 1 FROM service_assignments a WHERE a.organization_id=NEW.organization_id AND a.facility_id=NEW.id AND a.status IN('scheduled','active','suspended') AND(a.effective_to IS NULL OR a.effective_to>clock_timestamp()))THEN RAISE EXCEPTION 'facility has unresolved service assignment impact' USING ERRCODE='23514';END IF;
 RETURN NEW;
END $$;
