package com.rootopathy.careos.administration.infrastructure;
import com.rootopathy.careos.administration.application.*; import com.rootopathy.careos.administration.domain.OrganizationUnitDirectory; import com.rootopathy.careos.administration.domain.OrganizationUnitDirectory.Unit; import com.rootopathy.careos.tenancy.domain.AuthorizedTenantContext; import com.rootopathy.careos.tenancy.infrastructure.AuthorizedTenantTransactionGuard; import java.sql.Timestamp; import java.util.*; import org.springframework.jdbc.core.JdbcTemplate; import org.springframework.stereotype.Repository;
@Repository public class JdbcOrganizationUnitStore implements OrganizationUnitStore {
 private final JdbcTemplate jdbc; public JdbcOrganizationUnitStore(JdbcTemplate j){jdbc=j;}
 public OrganizationUnitDirectory directory(AuthorizedTenantContext c,UUID facilityId){AuthorizedTenantTransactionGuard.requireBound(jdbc,c);var units=jdbc.query("""
 SELECT id,parent_id,unit_code,unit_type,name,effective_from,effective_to,status,lock_version,created_at,updated_at FROM organization_units WHERE organization_id=? AND facility_id=? ORDER BY lower(name),id
 """,(r,n)->new Unit(r.getObject(1,UUID.class),r.getObject(2,UUID.class),r.getString(3),r.getString(4),r.getString(5),r.getTimestamp(6).toInstant(),r.getTimestamp(7)==null?null:r.getTimestamp(7).toInstant(),r.getString(8),r.getLong(9),r.getTimestamp(10).toInstant(),r.getTimestamp(11).toInstant()),c.organizationId(),facilityId);var permissions=permissions(c);return new OrganizationUnitDirectory(c.organizationId(),facilityId,permissions.contains(FacilityService.MANAGE),permissions.contains(OrganizationUnitService.LIFECYCLE),units,Objects.requireNonNull(jdbc.queryForObject("SELECT clock_timestamp()",Timestamp.class)).toInstant());}
 public Result create(AuthorizedTenantContext c,Draft d){AuthorizedTenantTransactionGuard.requireBound(jdbc,c);var id=jdbc.queryForObject("""
 INSERT INTO organization_units(organization_id,facility_id,parent_id,unit_code,unit_type,name,effective_from,effective_to,status,created_by,updated_by) VALUES(?,?,?,?,?,?,?,?, 'draft',?,?) RETURNING id
 """,UUID.class,c.organizationId(),d.facilityId(),d.parentId(),d.unitCode(),d.unitType(),d.name(),Timestamp.from(d.effectiveFrom()),d.effectiveTo()==null?null:Timestamp.from(d.effectiveTo()),c.actorId(),c.actorId());return new Result(directory(c,d.facilityId()),id,0);}
 public Result update(AuthorizedTenantContext c,UUID id,long revision,Draft d){AuthorizedTenantTransactionGuard.requireBound(jdbc,c);var changed=jdbc.update("""
 UPDATE organization_units SET unit_code=?,unit_type=?,name=?,effective_from=?,effective_to=?,lock_version=lock_version+1,updated_at=clock_timestamp(),updated_by=?
 WHERE organization_id=? AND facility_id=? AND id=? AND parent_id IS NOT DISTINCT FROM ? AND status='draft' AND lock_version=?
 """,d.unitCode(),d.unitType(),d.name(),Timestamp.from(d.effectiveFrom()),d.effectiveTo()==null?null:Timestamp.from(d.effectiveTo()),c.actorId(),c.organizationId(),d.facilityId(),id,d.parentId(),revision);if(changed!=1)throw new OrganizationUnitException(OrganizationUnitException.Reason.STALE,"Organization unit changed, moved, or is no longer an editable draft.");return new Result(directory(c,d.facilityId()),id,revision+1);}
 public LifecycleResult transition(AuthorizedTenantContext c,UUID facilityId,UUID id,long revision,String fromState,String toState){AuthorizedTenantTransactionGuard.requireBound(jdbc,c);if(!Set.of("draft:active","active:suspended","suspended:active").contains(fromState+":"+toState))throw new IllegalArgumentException("unsupported organization unit lifecycle transition");var state=jdbc.query("""
 SELECT u.parent_id,u.status,u.lock_version,u.effective_from,u.effective_to,f.status,
        CASE WHEN u.parent_id IS NULL THEN NULL ELSE p.status END
 FROM organization_units u JOIN facilities f ON f.organization_id=u.organization_id AND f.id=u.facility_id
 LEFT JOIN organization_units p ON p.organization_id=u.organization_id AND p.id=u.parent_id
 WHERE u.organization_id=? AND u.facility_id=? AND u.id=?
 """,r->r.next()?new Object[]{r.getObject(1,UUID.class),r.getString(2),r.getLong(3),r.getTimestamp(4).toInstant(),r.getTimestamp(5)==null?null:r.getTimestamp(5).toInstant(),r.getString(6),r.getString(7)}:null,c.organizationId(),facilityId,id);if(state==null)throw new OrganizationUnitException(OrganizationUnitException.Reason.NOT_FOUND,"Organization unit was not found.");if(!fromState.equals(state[1])||(long)state[2]!=revision)throw new OrganizationUnitException(OrganizationUnitException.Reason.STALE,"Organization unit changed or is no longer eligible for this lifecycle transition.");if("active".equals(toState)){if(!Set.of("under_review","active").contains(state[5]))throw new OrganizationUnitException(OrganizationUnitException.Reason.CONFLICT,"Organization unit activation requires an eligible facility.");var now=java.time.Instant.now();if(((java.time.Instant)state[3]).isAfter(now)||state[4]!=null&&!((java.time.Instant)state[4]).isAfter(now))throw new OrganizationUnitException(OrganizationUnitException.Reason.CONFLICT,"Organization unit activation requires a current effective range.");if(state[0]!=null&&!"active".equals(state[6]))throw new OrganizationUnitException(OrganizationUnitException.Reason.CONFLICT,"Organization unit activation requires an active parent.");}if("active".equals(fromState)&&"suspended".equals(toState)){var activeDescendant=Boolean.TRUE.equals(jdbc.queryForObject("""
 WITH RECURSIVE descendants(id,status) AS (SELECT id,status FROM organization_units WHERE organization_id=? AND parent_id=? UNION ALL SELECT u.id,u.status FROM organization_units u JOIN descendants d ON u.parent_id=d.id WHERE u.organization_id=?) SELECT EXISTS(SELECT 1 FROM descendants WHERE status='active')
 """,Boolean.class,c.organizationId(),id,c.organizationId()));if(activeDescendant)throw new OrganizationUnitException(OrganizationUnitException.Reason.CONFLICT,"Organization unit suspension requires all descendants to be non-active.");}var changed=jdbc.update("UPDATE organization_units SET status=?,lock_version=lock_version+1,updated_at=clock_timestamp(),updated_by=? WHERE organization_id=? AND facility_id=? AND id=? AND status=? AND lock_version=?",toState,c.actorId(),c.organizationId(),facilityId,id,fromState,revision);if(changed!=1)throw new OrganizationUnitException(OrganizationUnitException.Reason.STALE,"Organization unit changed before the lifecycle transition.");return new LifecycleResult(directory(c,facilityId),id,(UUID)state[0],fromState,revision+1);}
 public LifecycleResult close(AuthorizedTenantContext c,UUID facilityId,UUID id,long revision,java.time.Instant effectiveTo){AuthorizedTenantTransactionGuard.requireBound(jdbc,c);var state=jdbc.query("SELECT parent_id,status,lock_version,effective_from FROM organization_units WHERE organization_id=? AND facility_id=? AND id=?",r->r.next()?new Object[]{r.getObject(1,UUID.class),r.getString(2),r.getLong(3),r.getTimestamp(4).toInstant()}:null,c.organizationId(),facilityId,id);if(state==null)throw new OrganizationUnitException(OrganizationUnitException.Reason.NOT_FOUND,"Organization unit was not found.");if(!Set.of("active","suspended").contains(state[1])||(long)state[2]!=revision)throw new OrganizationUnitException(OrganizationUnitException.Reason.STALE,"Organization unit changed or is no longer eligible for closure.");if(!effectiveTo.isAfter((java.time.Instant)state[3]))throw new OrganizationUnitException(OrganizationUnitException.Reason.CONFLICT,"Organization unit closure must end after its effective start.");var openDescendant=Boolean.TRUE.equals(jdbc.queryForObject("""
 WITH RECURSIVE descendants(id,status) AS (SELECT id,status FROM organization_units WHERE organization_id=? AND parent_id=? UNION ALL SELECT u.id,u.status FROM organization_units u JOIN descendants d ON u.parent_id=d.id WHERE u.organization_id=?) SELECT EXISTS(SELECT 1 FROM descendants WHERE status<>'closed')
 """,Boolean.class,c.organizationId(),id,c.organizationId()));if(openDescendant)throw new OrganizationUnitException(OrganizationUnitException.Reason.CONFLICT,"Organization unit closure requires all descendants to be closed.");var changed=jdbc.update("UPDATE organization_units SET status='closed',effective_to=?,lock_version=lock_version+1,updated_at=clock_timestamp(),updated_by=? WHERE organization_id=? AND facility_id=? AND id=? AND status IN ('active','suspended') AND lock_version=?",Timestamp.from(effectiveTo),c.actorId(),c.organizationId(),facilityId,id,revision);if(changed!=1)throw new OrganizationUnitException(OrganizationUnitException.Reason.STALE,"Organization unit changed before closure.");return new LifecycleResult(directory(c,facilityId),id,(UUID)state[0],(String)state[1],revision+1);}
 public ReparentResult reparent(AuthorizedTenantContext c,UUID facilityId,UUID id,long revision,UUID parentId,java.time.Instant effectiveFrom){AuthorizedTenantTransactionGuard.requireBound(jdbc,c);var old=jdbc.query("SELECT parent_id,status,lock_version FROM organization_units WHERE organization_id=? AND facility_id=? AND id=?",r->r.next()?new Object[]{r.getObject(1,UUID.class),r.getString(2),r.getLong(3)}:null,c.organizationId(),facilityId,id);if(old==null)throw new OrganizationUnitException(OrganizationUnitException.Reason.NOT_FOUND,"Organization unit was not found.");if(!"draft".equals(old[1])||(long)old[2]!=revision)throw new OrganizationUnitException(OrganizationUnitException.Reason.STALE,"Organization unit changed or is no longer an editable draft.");var previous=(UUID)old[0];if(Objects.equals(previous,parentId))throw new OrganizationUnitException(OrganizationUnitException.Reason.CONFLICT,"The requested parent is already effective.");if(parentId!=null){var valid=Boolean.TRUE.equals(jdbc.queryForObject("SELECT EXISTS(SELECT 1 FROM organization_units WHERE organization_id=? AND facility_id=? AND id=? AND status='draft')",Boolean.class,c.organizationId(),facilityId,parentId));if(!valid)throw new OrganizationUnitException(OrganizationUnitException.Reason.CONFLICT,"Parent must be an eligible unit in the same facility.");var cycle=Boolean.TRUE.equals(jdbc.queryForObject("""
 WITH RECURSIVE descendants(id,depth) AS (SELECT id,1 FROM organization_units WHERE organization_id=? AND parent_id=? UNION ALL SELECT u.id,d.depth+1 FROM organization_units u JOIN descendants d ON u.parent_id=d.id WHERE u.organization_id=? AND d.depth<9) SELECT EXISTS(SELECT 1 FROM descendants WHERE id=?)
 """,Boolean.class,c.organizationId(),id,c.organizationId(),parentId));if(cycle)throw new OrganizationUnitException(OrganizationUnitException.Reason.CONFLICT,"Reparenting would create a hierarchy cycle.");var depth=jdbc.queryForObject("""
 WITH RECURSIVE ancestors(id,parent_id,depth) AS (SELECT id,parent_id,1 FROM organization_units WHERE organization_id=? AND id=? UNION ALL SELECT u.id,u.parent_id,a.depth+1 FROM organization_units u JOIN ancestors a ON u.id=a.parent_id WHERE u.organization_id=? AND a.depth<9) SELECT coalesce(max(depth),0) FROM ancestors
 """,Integer.class,c.organizationId(),parentId,c.organizationId());var subtree=jdbc.queryForObject("""
 WITH RECURSIVE descendants(id,depth) AS (SELECT id,1 FROM organization_units WHERE organization_id=? AND id=? UNION ALL SELECT u.id,d.depth+1 FROM organization_units u JOIN descendants d ON u.parent_id=d.id WHERE u.organization_id=? AND d.depth<9) SELECT coalesce(max(depth),1) FROM descendants
 """,Integer.class,c.organizationId(),id,c.organizationId());if(depth+subtree>8)throw new OrganizationUnitException(OrganizationUnitException.Reason.CONFLICT,"Reparenting would exceed hierarchy depth 8.");}var next=revision+1;jdbc.update("INSERT INTO organization_unit_parent_history(organization_id,unit_id,previous_parent_id,parent_id,effective_from,lock_version,changed_by) VALUES(?,?,?,?,?,?,?)",c.organizationId(),id,previous,parentId,Timestamp.from(effectiveFrom),next,c.actorId());var changed=jdbc.update("UPDATE organization_units SET parent_id=?,lock_version=?,updated_at=clock_timestamp(),updated_by=? WHERE organization_id=? AND facility_id=? AND id=? AND status='draft' AND lock_version=?",parentId,next,c.actorId(),c.organizationId(),facilityId,id,revision);if(changed!=1)throw new OrganizationUnitException(OrganizationUnitException.Reason.STALE,"Organization unit changed before reparenting.");return new ReparentResult(directory(c,facilityId),id,previous,parentId,next,effectiveFrom);}
 private Set<String> permissions(AuthorizedTenantContext c){return Set.copyOf(jdbc.queryForList("""
 SELECT DISTINCT p.permission_key FROM organization_memberships m JOIN authorization_roles r ON r.role_key=m.role_key JOIN authorization_role_permissions rp ON rp.role_key=r.role_key JOIN authorization_permissions p ON p.permission_key=rp.permission_key AND p.registry_version=r.registry_version WHERE m.organization_id=? AND m.user_id=? AND m.status='active' AND m.effective_from<=clock_timestamp() AND (m.effective_to IS NULL OR m.effective_to>clock_timestamp()) AND r.registry_version='m1-candidate-1' AND r.status='active' AND p.status='active'
 """,String.class,c.organizationId(),c.actorId()));}
}
