package com.rootopathy.careos.administration.infrastructure;

import com.rootopathy.careos.administration.application.ConfigurationActivationStore;
import com.rootopathy.careos.administration.domain.*;
import com.rootopathy.careos.tenancy.domain.AuthorizedTenantContext;
import java.sql.Timestamp;
import java.time.Instant;
import java.util.*;
import org.springframework.jdbc.core.JdbcTemplate;
import org.springframework.stereotype.Repository;

@Repository
public class JdbcConfigurationActivationStore implements ConfigurationActivationStore {
  private final JdbcTemplate jdbc;
  public JdbcConfigurationActivationStore(JdbcTemplate jdbc){this.jdbc=jdbc;}

  @Override public ConfigurationActivationDirectory directory(AuthorizedTenantContext c){
    var permissions=Set.copyOf(jdbc.queryForList("SELECT DISTINCT rp.permission_key FROM organization_memberships m JOIN authorization_role_permissions rp ON rp.role_key=m.role_key WHERE m.organization_id=? AND m.user_id=? AND m.status='active' AND m.effective_from<=clock_timestamp() AND (m.effective_to IS NULL OR m.effective_to>clock_timestamp())",String.class,c.organizationId(),c.actorId()));
    var evaluatedAt=now();
    var rows=jdbc.query("""
      SELECT v.id,v.display_number,v.parent_version_id,v.baseline_digest,v.change_summary,v.requested_effective_at,v.status,v.lock_version,v.maker_id,
             r.id,r.result_digest,r.blocker_count,r.warning_count,r.expires_at,a.id,a.decision,a.checker_id,a.expires_at,v.activated_at
      FROM configuration_versions v
      LEFT JOIN LATERAL (SELECT * FROM configuration_validation_results x WHERE x.organization_id=v.organization_id AND x.configuration_id=v.id ORDER BY x.evaluated_at DESC,x.id DESC LIMIT 1) r ON true
      LEFT JOIN LATERAL (SELECT * FROM configuration_approvals x WHERE x.organization_id=v.organization_id AND x.configuration_id=v.id ORDER BY x.decided_at DESC,x.id DESC LIMIT 1) a ON true
      WHERE v.organization_id=? ORDER BY v.created_at DESC,v.id DESC
      """,(r,n)->{
        var status=r.getString(7);var maker=r.getObject(9,UUID.class);
        var blockers=(Integer)r.getObject(12);var warnings=(Integer)r.getObject(13);
        var validationExpires=instant(r.getTimestamp(14));var decision=r.getString(16);
        var approvalExpires=instant(r.getTimestamp(18));
        var freshValidation=validationExpires!=null&&validationExpires.isAfter(evaluatedAt);
        return new ConfigurationActivationDirectory.Configuration(
            r.getObject(1,UUID.class),r.getString(2),r.getObject(3,UUID.class),r.getString(4),
            r.getString(5),r.getTimestamp(6).toInstant(),status,r.getLong(8),maker,
            permissions.contains("configuration.submit")&&c.actorId().equals(maker)
                &&"validated".equals(status)&&Integer.valueOf(0).equals(blockers)&&freshValidation,
            permissions.contains("configuration.approve")&&!c.actorId().equals(maker)
                &&"submitted".equals(status)&&Integer.valueOf(0).equals(blockers)&&freshValidation,
            permissions.contains("configuration.activate")&&!c.actorId().equals(maker)
                &&"approved".equals(status)&&"approved".equals(decision)&&freshValidation
                &&approvalExpires!=null&&approvalExpires.isAfter(evaluatedAt),
            r.getObject(10,UUID.class),r.getString(11),blockers==null?0:blockers,
            warnings==null?0:warnings,validationExpires,r.getObject(15,UUID.class),decision,
            r.getObject(17,UUID.class),approvalExpires,instant(r.getTimestamp(19)));
      },c.organizationId());
    var pending=jdbc.query("""
      SELECT subject_type,subject_id,lock_version,change_type,label,status FROM (
        SELECT 'facility' subject_type,id subject_id,lock_version,'activated' change_type,display_name label,status FROM facilities WHERE organization_id=? AND status='under_review'
        UNION ALL SELECT 'organization_unit',id,lock_version,'activated',name,status FROM organization_units WHERE organization_id=? AND status='draft'
        UNION ALL SELECT 'service_location',id,lock_version,'activated',name,status FROM service_locations WHERE organization_id=? AND status='draft'
        UNION ALL SELECT 'operating_hours_batch',id,lock_version,'activated',target_type||':'||target_id,status FROM operating_hours_batches WHERE organization_id=? AND status='scheduled'
        UNION ALL SELECT 'service_definition',id,lock_version,'activated',display_name,status FROM service_definitions WHERE organization_id=? AND status='draft'
        UNION ALL SELECT 'service_assignment',a.id,a.lock_version,'activated',s.display_name||' assignment',a.status FROM service_assignments a JOIN service_definitions s ON s.organization_id=a.organization_id AND s.id=a.service_id WHERE a.organization_id=? AND a.status='scheduled'
        UNION ALL SELECT 'identifier_scheme_version',v.id,v.lock_version,CASE WHEN v.status='active' THEN 'retired' ELSE 'activated' END,s.scheme_key||' v'||v.version_number,v.status FROM identifier_scheme_versions v JOIN identifier_schemes s ON s.organization_id=v.organization_id AND s.id=v.scheme_id WHERE v.organization_id=? AND v.status IN ('draft','active')
      ) pending ORDER BY subject_type,label,subject_id
      """,(r,n)->new ConfigurationActivationDirectory.PendingChange(r.getString(1),r.getObject(2,UUID.class),r.getLong(3),r.getString(4),r.getString(5),r.getString(6)),c.organizationId(),c.organizationId(),c.organizationId(),c.organizationId(),c.organizationId(),c.organizationId(),c.organizationId());
    return new ConfigurationActivationDirectory(c.organizationId(),permissions.contains("configuration.validation.run"),permissions.contains("configuration.submit"),permissions.contains("configuration.approve"),permissions.contains("configuration.activate"),pending,rows,evaluatedAt);
  }

  @Override public Baseline baseline(AuthorizedTenantContext c,UUID requested,long expected){
    UUID id=requested; boolean fresh=requested==null;
    if(fresh)id=jdbc.queryForObject("SELECT uuidv7()",UUID.class);
    else{
      var found=jdbc.queryForList("SELECT id FROM configuration_versions WHERE organization_id=? AND id=? AND ((status IN ('draft','validated') AND maker_id=?) OR status='approved') AND lock_version=?",UUID.class,c.organizationId(),id,c.actorId(),expected);
      if(found.isEmpty())throw new IllegalArgumentException("stale or unavailable configuration draft");
    }
    var parent=jdbc.query("SELECT id,COALESCE((SELECT result_digest FROM configuration_validation_results r WHERE r.organization_id=v.organization_id AND r.configuration_id=v.id ORDER BY evaluated_at DESC,id DESC LIMIT 1),baseline_digest) FROM configuration_versions v WHERE organization_id=? AND status='active' ORDER BY activated_at DESC,id DESC LIMIT 1",rs->rs.next()?new Object[]{rs.getObject(1,UUID.class),rs.getString(2)}:null,c.organizationId());
    long revision=Objects.requireNonNull(jdbc.queryForObject("SELECT lock_version FROM organizations WHERE id=?",Long.class,c.organizationId()));
    String state=jdbc.queryForObject("""
      SELECT jsonb_build_object('organization',jsonb_build_object('id',o.id,'lockVersion',o.lock_version,'status',o.status),
        'identifiers',(SELECT COALESCE(jsonb_agg(jsonb_build_array(id,lock_version,status,verification_status) ORDER BY id),'[]') FROM organization_identifiers WHERE organization_id=o.id),
        'addresses',(SELECT COALESCE(jsonb_agg(jsonb_build_array(id,lock_version,status,validation_status) ORDER BY id),'[]') FROM organization_addresses WHERE organization_id=o.id),
        'contacts',(SELECT COALESCE(jsonb_agg(jsonb_build_array(id,lock_version,status,verification_status) ORDER BY id),'[]') FROM organization_contacts WHERE organization_id=o.id),
        'internationalSettings',(SELECT COALESCE(jsonb_agg(jsonb_build_array(id,lock_version,status) ORDER BY id),'[]') FROM organization_international_settings WHERE organization_id=o.id),
        'governance',(SELECT COALESCE(jsonb_agg(jsonb_build_array(id,lock_version,status) ORDER BY id),'[]') FROM organization_governance_responsibilities WHERE organization_id=o.id),
        'facilities',(SELECT COALESCE(jsonb_agg(jsonb_build_array(id,lock_version,status) ORDER BY id),'[]') FROM facilities WHERE organization_id=o.id),
        'units',(SELECT COALESCE(jsonb_agg(jsonb_build_array(id,lock_version,status) ORDER BY id),'[]') FROM organization_units WHERE organization_id=o.id),
        'locations',(SELECT COALESCE(jsonb_agg(jsonb_build_array(id,lock_version,status) ORDER BY id),'[]') FROM service_locations WHERE organization_id=o.id),
        'hours',(SELECT COALESCE(jsonb_agg(jsonb_build_object('id',b.id,'revision',b.lock_version,'status',b.status,'intervals',(SELECT COALESCE(jsonb_agg(jsonb_build_array(i.weekday,i.start_minute,i.end_minute,i.ends_next_day) ORDER BY i.weekday,i.start_minute),'[]') FROM operating_hours_intervals i WHERE i.organization_id=b.organization_id AND i.batch_id=b.id),'exceptions',(SELECT COALESCE(jsonb_agg(jsonb_build_object('date',e.local_date,'closed',e.closed,'label',e.label,'reason',e.reason_code,'intervals',(SELECT COALESCE(jsonb_agg(jsonb_build_array(x.start_minute,x.end_minute,x.ends_next_day) ORDER BY x.start_minute),'[]') FROM operating_hours_exception_intervals x WHERE x.organization_id=e.organization_id AND x.exception_id=e.id)) ORDER BY e.local_date),'[]') FROM operating_hours_exceptions e WHERE e.organization_id=b.organization_id AND e.batch_id=b.id)) ORDER BY b.id),'[]') FROM operating_hours_batches b WHERE b.organization_id=o.id),
        'services',(SELECT COALESCE(jsonb_agg(jsonb_build_array(id,lock_version,status) ORDER BY id),'[]') FROM service_definitions WHERE organization_id=o.id),
        'assignments',(SELECT COALESCE(jsonb_agg(jsonb_build_array(id,lock_version,status) ORDER BY id),'[]') FROM service_assignments WHERE organization_id=o.id),
        'schemes',(SELECT COALESCE(jsonb_agg(jsonb_build_array(id,lock_version,status) ORDER BY id),'[]') FROM identifier_schemes WHERE organization_id=o.id),
        'schemeVersions',(SELECT COALESCE(jsonb_agg(jsonb_build_array(id,lock_version,status) ORDER BY id),'[]') FROM identifier_scheme_versions WHERE organization_id=o.id),
        'memberships',(SELECT COALESCE(jsonb_agg(jsonb_build_array(id,lock_version,status) ORDER BY id),'[]') FROM organization_memberships WHERE organization_id=o.id))::text
      FROM organizations o WHERE o.id=?
      """,String.class,c.organizationId());
    return new Baseline(id,fresh,parent==null?null:(UUID)parent[0],parent==null?null:(String)parent[1],revision,state);
  }

  @Override public ActivationEvidence activationEvidence(AuthorizedTenantContext c,UUID id){
    var version=jdbc.query("SELECT baseline_digest,baseline_revision,parent_version_id,parent_digest FROM configuration_versions WHERE organization_id=? AND id=?",rs->rs.next()?new Object[]{rs.getString(1),rs.getLong(2),rs.getObject(3,UUID.class),rs.getString(4)}:null,c.organizationId(),id);
    if(version==null)throw new IllegalArgumentException("configuration is unavailable");
    var snapshot=baseline(c,id,Objects.requireNonNull(jdbc.queryForObject("SELECT lock_version FROM configuration_versions WHERE organization_id=? AND id=?",Long.class,c.organizationId(),id)));
    return new ActivationEvidence((String)version[0],(Long)version[1],(UUID)version[2],(String)version[3],snapshot.canonicalState());
  }

  @Override public Set<String> candidateSatisfiedGates(AuthorizedTenantContext c,List<ChangeItem> changes){
    var selected=new HashMap<String,Set<UUID>>();for(var item:changes)if("activated".equals(item.changeType()))selected.computeIfAbsent(item.subjectType(),ignored->new HashSet<>()).add(item.subjectId());
    var satisfied=new HashSet<String>();
    // baseline() binds the exact organization revision, parent version/digest and canonical state,
    // while validate() checks every immutable typed change in the same governed transaction.  The
    // candidate therefore supplies the configuration anchor that is necessarily absent for an
    // organization's first activation; later mutations invalidate the persisted result in V48.
    satisfied.add("configuration.integrity");
    var facilities=jdbc.queryForList("SELECT f.id FROM facilities f JOIN organizations o ON o.id=f.organization_id JOIN organization_addresses a ON a.organization_id=f.organization_id AND a.id=f.address_id WHERE f.organization_id=? AND f.status IN ('under_review','active') AND a.status='active' AND a.validation_status='validated' AND (f.timezone IS NOT NULL OR o.timezone IS NOT NULL)",UUID.class,c.organizationId());
    if(!facilities.isEmpty()&&facilities.stream().anyMatch(id->activeOrSelected("facilities",id,selected.get("facility"),c)))satisfied.add("network.facility.minimum");
    boolean hierarchy=!facilities.isEmpty()&&facilities.stream().allMatch(facility->Boolean.TRUE.equals(jdbc.queryForObject("SELECT EXISTS(SELECT 1 FROM organization_units WHERE organization_id=? AND facility_id=? AND status='active') OR EXISTS(SELECT 1 FROM service_locations WHERE organization_id=? AND facility_id=? AND status='active')",Boolean.class,c.organizationId(),facility,c.organizationId(),facility))||selectedForFacility(c,"organization_units",facility,selected.get("organization_unit"))||selectedForFacility(c,"service_locations",facility,selected.get("service_location")));
    if(hierarchy)satisfied.add("network.hierarchy.valid");
    boolean hours=!facilities.isEmpty()&&facilities.stream().allMatch(facility->Boolean.TRUE.equals(jdbc.queryForObject("SELECT EXISTS(SELECT 1 FROM operating_hours_batches WHERE organization_id=? AND target_type='facility' AND target_id=? AND status='active')",Boolean.class,c.organizationId(),facility))||selectedHoursForFacility(c,facility,selected.get("operating_hours_batch")));
    if(hours)satisfied.add("network.hours.valid");
    var services=new HashSet<>(jdbc.queryForList("SELECT id FROM service_definitions WHERE organization_id=? AND status='active' AND owner_responsibility_id IS NOT NULL",UUID.class,c.organizationId()));if(selected.get("service_definition")!=null)for(var id:selected.get("service_definition"))if(Boolean.TRUE.equals(jdbc.queryForObject("SELECT EXISTS(SELECT 1 FROM service_definitions WHERE organization_id=? AND id=? AND status='draft' AND owner_responsibility_id IS NOT NULL)",Boolean.class,c.organizationId(),id)))services.add(id);if(!services.isEmpty())satisfied.add("service.catalogue.active");
    boolean assignments=!services.isEmpty()&&services.stream().allMatch(service->Boolean.TRUE.equals(jdbc.queryForObject("SELECT EXISTS(SELECT 1 FROM service_assignments WHERE organization_id=? AND service_id=? AND status='active')",Boolean.class,c.organizationId(),service))||selectedAssignmentForService(c,service,selected.get("service_assignment")));if(assignments)satisfied.add("service.assignment.valid");
    var schemes=jdbc.queryForList("SELECT id FROM identifier_schemes WHERE organization_id=? AND status<>'retired'",UUID.class,c.organizationId());boolean schemeReady=!schemes.isEmpty()&&schemes.stream().allMatch(scheme->Boolean.TRUE.equals(jdbc.queryForObject("SELECT EXISTS(SELECT 1 FROM identifier_scheme_versions WHERE organization_id=? AND scheme_id=? AND status='active')",Boolean.class,c.organizationId(),scheme))||selectedVersionForScheme(c,scheme,selected.get("identifier_scheme_version")));if(schemeReady)satisfied.add("identifier.scheme.active");
    return Set.copyOf(satisfied);
  }
  private boolean activeOrSelected(String table,UUID id,Set<UUID> selected,AuthorizedTenantContext c){return Boolean.TRUE.equals(jdbc.queryForObject("SELECT status='active' FROM "+table+" WHERE organization_id=? AND id=?",Boolean.class,c.organizationId(),id))||selected!=null&&selected.contains(id);}
  private boolean selectedForFacility(AuthorizedTenantContext c,String table,UUID facility,Set<UUID> ids){if(ids==null)return false;for(var id:ids)if(Boolean.TRUE.equals(jdbc.queryForObject("SELECT EXISTS(SELECT 1 FROM "+table+" WHERE organization_id=? AND id=? AND facility_id=?)",Boolean.class,c.organizationId(),id,facility)))return true;return false;}
  private boolean selectedHoursForFacility(AuthorizedTenantContext c,UUID facility,Set<UUID> ids){if(ids==null)return false;for(var id:ids)if(Boolean.TRUE.equals(jdbc.queryForObject("SELECT EXISTS(SELECT 1 FROM operating_hours_batches WHERE organization_id=? AND id=? AND target_type='facility' AND target_id=?)",Boolean.class,c.organizationId(),id,facility)))return true;return false;}
  private boolean selectedAssignmentForService(AuthorizedTenantContext c,UUID service,Set<UUID> ids){if(ids==null)return false;for(var id:ids)if(Boolean.TRUE.equals(jdbc.queryForObject("SELECT EXISTS(SELECT 1 FROM service_assignments WHERE organization_id=? AND id=? AND service_id=?)",Boolean.class,c.organizationId(),id,service)))return true;return false;}
  private boolean selectedVersionForScheme(AuthorizedTenantContext c,UUID scheme,Set<UUID> ids){if(ids==null)return false;for(var id:ids)if(Boolean.TRUE.equals(jdbc.queryForObject("SELECT EXISTS(SELECT 1 FROM identifier_scheme_versions WHERE organization_id=? AND id=? AND scheme_id=?)",Boolean.class,c.organizationId(),id,scheme)))return true;return false;}

  @Override public ValidationResult validate(AuthorizedTenantContext c,ValidationDraft d,AdministrationReadiness readiness,String gatesJson,String digest){
    UUID id=d.configurationId(); long revision;
    if(d.newConfiguration()){
      jdbc.update("INSERT INTO configuration_versions(id,organization_id,display_number,parent_version_id,parent_digest,baseline_revision,baseline_digest,change_summary,reason,requested_effective_at,maker_id,correlation_id,updated_by) VALUES(?,?,('CFG-'||to_char(clock_timestamp(),'YYYY')||'-'||lpad(nextval('configuration_display_number_seq')::text,6,'0')),?,?,?,?,?,?,?,?,?,?,?)",id,c.organizationId(),d.parentVersionId(),d.parentDigest(),d.baselineRevision(),d.baselineDigest(),d.changeSummary(),d.reason(),Timestamp.from(d.requestedEffectiveAt()),c.actorId(),c.correlationId(),c.actorId()); revision=0;
    }else{
      var owner=jdbc.queryForObject("SELECT maker_id FROM configuration_versions WHERE organization_id=? AND id=? AND status IN ('draft','validated') AND lock_version=? FOR UPDATE",UUID.class,c.organizationId(),id,d.expectedRevision());
      if(owner==null||!owner.equals(c.actorId()))throw new IllegalArgumentException("stale or unavailable configuration draft"); revision=d.expectedRevision();
    }
    if(d.newConfiguration())for(var item:d.changeItems()){validateChange(c,item);jdbc.update("INSERT INTO configuration_change_items(organization_id,configuration_id,subject_type,subject_id,baseline_revision,new_revision,change_type) VALUES(?,?,?,?,?,?,?)",c.organizationId(),id,item.subjectType(),item.subjectId(),item.expectedRevision(),item.expectedRevision()+1,item.changeType());}
    else{var stored=jdbc.query("SELECT subject_type,subject_id,baseline_revision,change_type FROM configuration_change_items WHERE organization_id=? AND configuration_id=? ORDER BY subject_type,subject_id",(r,n)->new ChangeItem(r.getString(1),r.getObject(2,UUID.class),r.getLong(3),r.getString(4)),c.organizationId(),id);if(!stored.equals(d.changeItems()))throw new IllegalArgumentException("configuration change set is immutable");for(var item:stored)validateChange(c,item);}
    jdbc.update("UPDATE configuration_validation_results SET invalidated_at=clock_timestamp(),invalidation_code='revalidated' WHERE organization_id=? AND configuration_id=? AND invalidated_at IS NULL",c.organizationId(),id);
    var expires=now().plusSeconds(900);
    var resultId=jdbc.queryForObject("INSERT INTO configuration_validation_results(organization_id,configuration_id,configuration_revision,result_digest,parent_digest,gate_catalogue_version,gates,blocker_count,warning_count,evaluated_at,expires_at,evaluated_by) VALUES(?,?,?,?,?,?,?::jsonb,?,?,?, ?,?) RETURNING id",UUID.class,c.organizationId(),id,revision,digest,d.parentDigest(),readiness.catalogueVersion(),gatesJson,readiness.blockedGates(),readiness.warningGates(),Timestamp.from(expires.minusSeconds(900)),Timestamp.from(expires),c.actorId());
    var changed=jdbc.update("UPDATE configuration_versions SET status='validated',lock_version=lock_version+1,updated_at=clock_timestamp(),updated_by=? WHERE organization_id=? AND id=? AND status IN ('draft','validated') AND lock_version=?",c.actorId(),c.organizationId(),id,revision);
    if(changed!=1)throw new IllegalArgumentException("configuration changed during validation");
    return new ValidationResult(id,resultId,digest,readiness.blockedGates(),readiness.warningGates(),expires,revision+1,directory(c));
  }
  @Override public Result submit(AuthorizedTenantContext c,UUID id,long revision,UUID resultId,String digest){
    var valid=Boolean.TRUE.equals(jdbc.queryForObject("SELECT EXISTS(SELECT 1 FROM configuration_validation_results WHERE organization_id=? AND configuration_id=? AND id=? AND result_digest=? AND blocker_count=0 AND invalidated_at IS NULL AND expires_at>clock_timestamp())",Boolean.class,c.organizationId(),id,resultId,digest));if(!valid)throw new IllegalArgumentException("fresh blocker-free validation required");
    var n=jdbc.update("UPDATE configuration_versions SET status='submitted',submitted_at=clock_timestamp(),lock_version=lock_version+1,updated_at=clock_timestamp(),updated_by=? WHERE organization_id=? AND id=? AND status='validated' AND maker_id=? AND lock_version=?",c.actorId(),c.organizationId(),id,c.actorId(),revision);if(n!=1)throw new IllegalArgumentException("stale or unavailable configuration");return new Result(id,resultId,digest,revision+1,directory(c));
  }
  @Override public DecisionResult decide(AuthorizedTenantContext c,UUID id,long revision,UUID resultId,String digest,boolean approve,String code,String reason){
    var row=jdbc.query("SELECT maker_id,expires_at,invalidated_at,blocker_count FROM configuration_validation_results r JOIN configuration_versions v ON v.organization_id=r.organization_id AND v.id=r.configuration_id WHERE r.organization_id=? AND r.configuration_id=? AND r.id=? AND r.result_digest=? AND v.status='submitted' AND v.lock_version=? FOR UPDATE OF v",rs->rs.next()?new Object[]{rs.getObject(1,UUID.class),rs.getTimestamp(2).toInstant(),rs.getTimestamp(3),rs.getInt(4)}:null,c.organizationId(),id,resultId,digest,revision);if(row==null||row[0].equals(c.actorId())||((Instant)row[1]).compareTo(now())<=0||row[2]!=null||((Integer)row[3])>0)throw new IllegalArgumentException("configuration is not eligible for independent decision");
    var decision=approve?"approved":"rejected";var approvalId=jdbc.queryForObject("INSERT INTO configuration_approvals(organization_id,configuration_id,validation_result_id,result_digest,maker_id,checker_id,decision,decision_code,reason,decided_at,expires_at,policy_version) SELECT ?,?,?,?,?,?,?,?,?,t,t+interval '30 minutes','m1-candidate-1' FROM (SELECT clock_timestamp() t) clock RETURNING id",UUID.class,c.organizationId(),id,resultId,digest,row[0],c.actorId(),decision,code,reason);
    var n=jdbc.update("UPDATE configuration_versions SET status=?,approved_at=CASE WHEN ?='approved' THEN clock_timestamp() ELSE NULL END,lock_version=lock_version+1,updated_at=clock_timestamp(),updated_by=? WHERE organization_id=? AND id=? AND status='submitted' AND lock_version=?",decision,decision,c.actorId(),c.organizationId(),id,revision);if(n!=1)throw new IllegalArgumentException("configuration changed during decision");return new DecisionResult(id,approvalId,digest,code,revision+1,directory(c));
  }
  @Override public Result activate(AuthorizedTenantContext c,UUID id,long revision,UUID approvalId,String digest,Instant effective){
    var maker=jdbc.queryForObject("SELECT maker_id FROM configuration_versions WHERE organization_id=? AND id=? AND status='approved' AND lock_version=? FOR UPDATE",UUID.class,c.organizationId(),id,revision);if(maker==null||maker.equals(c.actorId()))throw new IllegalArgumentException("activator must differ from maker");
    var eligible=Boolean.TRUE.equals(jdbc.queryForObject("SELECT EXISTS(SELECT 1 FROM configuration_approvals a JOIN configuration_validation_results r ON r.organization_id=a.organization_id AND r.id=a.validation_result_id WHERE a.organization_id=? AND a.configuration_id=? AND a.id=? AND a.decision='approved' AND a.result_digest=? AND a.invalidated_at IS NULL AND a.expires_at>clock_timestamp() AND r.invalidated_at IS NULL AND r.expires_at>clock_timestamp())",Boolean.class,c.organizationId(),id,approvalId,digest));if(!eligible)throw new IllegalArgumentException("fresh independent approval required");
    var active=jdbc.queryForList("SELECT id FROM configuration_versions WHERE organization_id=? AND status='active' FOR UPDATE",UUID.class,c.organizationId());var previous=active.isEmpty()?null:active.getFirst();
    var run=jdbc.queryForObject("INSERT INTO configuration_activation_runs(organization_id,configuration_id,approval_id,activator_id,result_digest,effective_from,previous_version_id,status,correlation_id) VALUES(?,?,?,?,?,?,?,'running',?) RETURNING id",UUID.class,c.organizationId(),id,approvalId,c.actorId(),digest,Timestamp.from(effective),previous,c.correlationId());
    var changes=new ArrayList<>(jdbc.query("SELECT subject_type,subject_id,baseline_revision,change_type FROM configuration_change_items WHERE organization_id=? AND configuration_id=?",(r,n)->new ChangeItem(r.getString(1),r.getObject(2,UUID.class),r.getLong(3),r.getString(4)),c.organizationId(),id));changes.sort(Comparator.comparingInt((ChangeItem item)->activationOrder(c,item)).thenComparing(item->item.subjectId().toString()));for(var change:changes)activateChange(c,change,effective);
    if(previous!=null)jdbc.update("UPDATE configuration_versions SET status='superseded',superseded_at=clock_timestamp(),lock_version=lock_version+1,updated_at=clock_timestamp(),updated_by=? WHERE organization_id=? AND id=? AND status='active'",c.actorId(),c.organizationId(),previous);
    var n=jdbc.update("UPDATE configuration_versions SET status='active',activated_at=clock_timestamp(),lock_version=lock_version+1,updated_at=clock_timestamp(),updated_by=? WHERE organization_id=? AND id=? AND status='approved' AND lock_version=?",c.actorId(),c.organizationId(),id,revision);if(n!=1)throw new IllegalArgumentException("configuration changed during activation");
    jdbc.update("UPDATE configuration_activation_runs SET status='activated',completed_at=clock_timestamp() WHERE organization_id=? AND id=?",c.organizationId(),run);return new Result(id,null,digest,revision+1,directory(c));
  }
  private void validateChange(AuthorizedTenantContext c,ChangeItem item){var table=switch(item.subjectType()){case "facility"->"facilities";case "organization_unit"->"organization_units";case "service_location"->"service_locations";case "operating_hours_batch"->"operating_hours_batches";case "service_definition"->"service_definitions";case "service_assignment"->"service_assignments";case "identifier_scheme_version"->"identifier_scheme_versions";default->throw new IllegalArgumentException("unsupported configuration subject");};var rows=jdbc.queryForList("SELECT status FROM "+table+" WHERE organization_id=? AND id=? AND lock_version=?",String.class,c.organizationId(),item.subjectId(),item.expectedRevision());if(rows.isEmpty())throw new IllegalArgumentException("configuration subject revision is unavailable");var status=rows.getFirst();var eligible=switch(item.changeType()){case "activated"->Set.of("under_review","draft","scheduled").contains(status);case "retired"->"active".equals(status);case "closed"->Set.of("active","suspended").contains(status);case "ended"->Set.of("active","suspended").contains(status);default->false;};if(!eligible)throw new IllegalArgumentException("configuration subject lifecycle is ineligible");}
  private int activationOrder(AuthorizedTenantContext c,ChangeItem item){int base=switch(item.subjectType()){case "operating_hours_batch"->100;case "organization_unit"->200;case "service_location"->300;case "service_definition"->400;case "service_assignment"->500;case "identifier_scheme_version"->"retired".equals(item.changeType())?590:600;case "facility"->700;default->900;};Integer depth=null;if(item.subjectType().equals("organization_unit"))depth=jdbc.queryForObject("WITH RECURSIVE a(id,parent_id,depth) AS(SELECT id,parent_id,0 FROM organization_units WHERE organization_id=? AND id=? UNION ALL SELECT p.id,p.parent_id,a.depth+1 FROM organization_units p JOIN a ON p.id=a.parent_id WHERE p.organization_id=? AND a.depth<8)SELECT max(depth) FROM a",Integer.class,c.organizationId(),item.subjectId(),c.organizationId());else if(item.subjectType().equals("service_location"))depth=jdbc.queryForObject("WITH RECURSIVE a(id,parent_id,depth) AS(SELECT id,parent_id,0 FROM service_locations WHERE organization_id=? AND id=? UNION ALL SELECT p.id,p.parent_id,a.depth+1 FROM service_locations p JOIN a ON p.id=a.parent_id WHERE p.organization_id=? AND a.depth<8)SELECT max(depth) FROM a",Integer.class,c.organizationId(),item.subjectId(),c.organizationId());if(depth==null)return base;return base+("closed".equals(item.changeType())?8-depth:depth);}
  private void activateChange(AuthorizedTenantContext c,ChangeItem item,Instant effective){validateChange(c,item);int changed=switch(item.subjectType()){case "facility"->jdbc.update("UPDATE facilities SET status=?,closed_at=CASE WHEN ?='closed' THEN clock_timestamp() ELSE closed_at END,lock_version=lock_version+1,updated_at=clock_timestamp(),updated_by=? WHERE organization_id=? AND id=? AND lock_version=?",item.changeType().equals("closed")?"closed":"active",item.changeType(),c.actorId(),c.organizationId(),item.subjectId(),item.expectedRevision());case "organization_unit"->jdbc.update("UPDATE organization_units SET status=?,effective_to=CASE WHEN ?='closed' THEN clock_timestamp() ELSE effective_to END,lock_version=lock_version+1,updated_at=clock_timestamp(),updated_by=? WHERE organization_id=? AND id=? AND lock_version=?",item.changeType().equals("closed")?"closed":"active",item.changeType(),c.actorId(),c.organizationId(),item.subjectId(),item.expectedRevision());case "service_location"->jdbc.update("UPDATE service_locations SET status=?,effective_to=CASE WHEN ?='closed' THEN clock_timestamp() ELSE effective_to END,lock_version=lock_version+1,updated_at=clock_timestamp(),updated_by=? WHERE organization_id=? AND id=? AND lock_version=?",item.changeType().equals("closed")?"closed":"active",item.changeType(),c.actorId(),c.organizationId(),item.subjectId(),item.expectedRevision());case "operating_hours_batch"->activateHours(c,item,effective);case "service_definition"->jdbc.update("UPDATE service_definitions SET status=?,retirement_reason=CASE WHEN ?='retired' THEN current_setting('app.current_authorization_reason',true) ELSE retirement_reason END,lock_version=lock_version+1,updated_at=clock_timestamp(),updated_by=? WHERE organization_id=? AND id=? AND lock_version=?",item.changeType().equals("retired")?"retired":"active",item.changeType(),c.actorId(),c.organizationId(),item.subjectId(),item.expectedRevision());case "service_assignment"->jdbc.update("UPDATE service_assignments SET status=?,lock_version=lock_version+1,updated_at=clock_timestamp(),updated_by=? WHERE organization_id=? AND id=? AND lock_version=?",item.changeType().equals("ended")?"ended":"active",c.actorId(),c.organizationId(),item.subjectId(),item.expectedRevision());case "identifier_scheme_version"->activateSchemeVersion(c,item,effective);default->0;};if(changed!=1)throw new IllegalArgumentException("configuration subject changed during activation");}
  private int activateHours(AuthorizedTenantContext c,ChangeItem item,Instant effective){var target=jdbc.queryForMap("SELECT target_type,target_id FROM operating_hours_batches WHERE organization_id=? AND id=?",c.organizationId(),item.subjectId());jdbc.update("UPDATE operating_hours_batches SET status='superseded',effective_to=?,lock_version=lock_version+1,updated_at=clock_timestamp(),updated_by=? WHERE organization_id=? AND target_type=? AND target_id=? AND status='active'",Timestamp.from(effective),c.actorId(),c.organizationId(),target.get("target_type"),target.get("target_id"));return jdbc.update("UPDATE operating_hours_batches SET status='active',effective_from=?,lock_version=lock_version+1,updated_at=clock_timestamp(),updated_by=? WHERE organization_id=? AND id=? AND lock_version=?",Timestamp.from(effective),c.actorId(),c.organizationId(),item.subjectId(),item.expectedRevision());}
  private int activateSchemeVersion(AuthorizedTenantContext c,ChangeItem item,Instant effective){var scheme=jdbc.queryForObject("SELECT scheme_id FROM identifier_scheme_versions WHERE organization_id=? AND id=?",UUID.class,c.organizationId(),item.subjectId());var status=item.changeType().equals("retired")?"retired":"active";var changed=jdbc.update("UPDATE identifier_scheme_versions SET status=?,activated_at=CASE WHEN ?='active' THEN clock_timestamp() ELSE activated_at END,activated_by=CASE WHEN ?='active' THEN ? ELSE activated_by END,retired_at=CASE WHEN ?='retired' THEN clock_timestamp() ELSE retired_at END,retired_by=CASE WHEN ?='retired' THEN ? ELSE retired_by END,lock_version=lock_version+1 WHERE organization_id=? AND id=? AND lock_version=?",status,status,status,c.actorId(),status,status,c.actorId(),c.organizationId(),item.subjectId(),item.expectedRevision());if(changed==1)jdbc.update("UPDATE identifier_schemes SET status=?,lock_version=lock_version+1,updated_at=clock_timestamp(),updated_by=? WHERE organization_id=? AND id=?",status,c.actorId(),c.organizationId(),scheme);return changed;}
  private Instant now(){return Objects.requireNonNull(jdbc.queryForObject("SELECT clock_timestamp()",Timestamp.class)).toInstant();}private static Instant instant(Timestamp value){return value==null?null:value.toInstant();}
}
