package com.rootopathy.careos.administration.infrastructure;

import com.rootopathy.careos.administration.application.OperatingHoursStore;
import com.rootopathy.careos.administration.domain.OperatingHoursDirectory;
import com.rootopathy.careos.administration.domain.OperatingHoursOverview;
import com.rootopathy.careos.tenancy.domain.AuthorizedTenantContext;
import java.sql.Timestamp;
import java.time.Instant;
import java.util.*;
import org.springframework.jdbc.core.JdbcTemplate;
import org.springframework.stereotype.Repository;

@Repository public class JdbcOperatingHoursStore implements OperatingHoursStore {
 private final JdbcTemplate jdbc; public JdbcOperatingHoursStore(JdbcTemplate jdbc){this.jdbc=jdbc;}
 @Override public OperatingHoursOverview overview(AuthorizedTenantContext c){var batches=jdbc.query("SELECT id,target_type,target_id,timezone,effective_from,effective_to,status,lock_version FROM operating_hours_batches WHERE organization_id=? ORDER BY effective_from DESC,id",(r,n)->new OperatingHoursOverview.Batch(r.getObject(1,UUID.class),r.getString(2),r.getObject(3,UUID.class),r.getString(4),r.getTimestamp(5).toInstant(),r.getTimestamp(6)==null?null:r.getTimestamp(6).toInstant(),r.getString(7),r.getLong(8)),c.organizationId());var can=Boolean.TRUE.equals(jdbc.queryForObject("SELECT EXISTS(SELECT 1 FROM authorization_role_permissions rp JOIN organization_memberships m ON m.role_key=rp.role_key WHERE m.organization_id=? AND m.user_id=? AND m.status='active' AND rp.permission_key='network.hours.manage')",Boolean.class,c.organizationId(),c.actorId()));return new OperatingHoursOverview(c.organizationId(),can,batches,dbNow());}
 @Override public OperatingHoursDirectory directory(AuthorizedTenantContext c,String type,UUID target){
  var batches=jdbc.query("SELECT id,timezone,effective_from,effective_to,status,lock_version FROM operating_hours_batches WHERE organization_id=? AND target_type=? AND target_id=? ORDER BY effective_from DESC,id",(rs,n)->{
   var id=rs.getObject("id",UUID.class); var to=rs.getTimestamp("effective_to");
   var intervals=jdbc.query("SELECT weekday,start_minute,end_minute,ends_next_day FROM operating_hours_intervals WHERE organization_id=? AND batch_id=? ORDER BY weekday,start_minute",(ir,x)->new OperatingHoursDirectory.Interval(ir.getInt(1),ir.getInt(2),ir.getInt(3),ir.getBoolean(4)),c.organizationId(),id);
   var exceptions=jdbc.query("SELECT id,local_date,closed,label,reason_code FROM operating_hours_exceptions WHERE organization_id=? AND batch_id=? ORDER BY local_date",(er,x)->{var eid=er.getObject(1,UUID.class);var replacement=jdbc.query("SELECT start_minute,end_minute,ends_next_day FROM operating_hours_exception_intervals WHERE organization_id=? AND exception_id=? ORDER BY start_minute",(rr,y)->new OperatingHoursDirectory.ExceptionInterval(rr.getInt(1),rr.getInt(2),rr.getBoolean(3)),c.organizationId(),eid);return new OperatingHoursDirectory.ExceptionDay(er.getObject(2,java.time.LocalDate.class),er.getBoolean(3),er.getString(4),er.getString(5),replacement);},c.organizationId(),id);
   return new OperatingHoursDirectory.Batch(id,rs.getString("timezone"),rs.getTimestamp("effective_from").toInstant(),to==null?null:to.toInstant(),rs.getString("status"),rs.getLong("lock_version"),intervals,exceptions);
  },c.organizationId(),type,target);
  var can=Boolean.TRUE.equals(jdbc.queryForObject("SELECT EXISTS(SELECT 1 FROM authorization_role_permissions rp JOIN organization_memberships m ON m.role_key=rp.role_key WHERE m.organization_id=? AND m.user_id=? AND m.status='active' AND rp.permission_key='network.hours.manage')",Boolean.class,c.organizationId(),c.actorId()));
  return new OperatingHoursDirectory(c.organizationId(),type,target,can,batches,dbNow());
 }
 @Override public MutationResult create(AuthorizedTenantContext c,Draft d){var id=jdbc.queryForObject("INSERT INTO operating_hours_batches(organization_id,target_type,target_id,timezone,effective_from,effective_to,created_by,updated_by) VALUES(?,?,?,?,?,?,?,?) RETURNING id",UUID.class,c.organizationId(),d.targetType(),d.targetId(),d.timezone(),Timestamp.from(d.effectiveFrom()),d.effectiveTo()==null?null:Timestamp.from(d.effectiveTo()),c.actorId(),c.actorId());for(var i:d.intervals())jdbc.update("INSERT INTO operating_hours_intervals(organization_id,batch_id,weekday,start_minute,end_minute,ends_next_day) VALUES(?,?,?,?,?,?)",c.organizationId(),id,i.weekday(),i.startMinute(),i.endMinute(),i.endsNextDay());for(var e:d.exceptions()){var eid=jdbc.queryForObject("INSERT INTO operating_hours_exceptions(organization_id,batch_id,local_date,closed,label,reason_code) VALUES(?,?,?,?,?,?) RETURNING id",UUID.class,c.organizationId(),id,e.localDate(),e.closed(),e.label(),e.reasonCode());for(var i:e.intervals())jdbc.update("INSERT INTO operating_hours_exception_intervals(organization_id,exception_id,start_minute,end_minute,ends_next_day) VALUES(?,?,?,?,?)",c.organizationId(),eid,i.startMinute(),i.endMinute(),i.endsNextDay());}var state=d.effectiveFrom().isAfter(dbNow())?"scheduled":"active";if(state.equals("active"))jdbc.update("UPDATE operating_hours_batches SET status='superseded',lock_version=lock_version+1,updated_at=clock_timestamp(),updated_by=? WHERE organization_id=? AND target_type=? AND target_id=? AND status='active' AND id<>?",c.actorId(),c.organizationId(),d.targetType(),d.targetId(),id);jdbc.update("UPDATE operating_hours_batches SET status=?,lock_version=1,updated_at=clock_timestamp(),updated_by=? WHERE organization_id=? AND id=?",state,c.actorId(),c.organizationId(),id);return new MutationResult(id,"draft",state,d.effectiveFrom(),directory(c,d.targetType(),d.targetId()));}
 @Override public MutationResult transition(AuthorizedTenantContext c,String type,UUID target,UUID id,long revision,String to){var row=jdbc.query("SELECT status,effective_from FROM operating_hours_batches WHERE organization_id=? AND target_type=? AND target_id=? AND id=?",rs->rs.next()?Map.of("status",rs.getString(1),"from",rs.getTimestamp(2).toInstant()):null,c.organizationId(),type,target,id);if(row==null)throw new IllegalArgumentException("operating-hours batch is unavailable");var from=(String)row.get("status");if(to.equals("cancelled")&&!Set.of("draft","scheduled").contains(from)||Set.of("active","superseded","cancelled").contains(from)&&!to.equals("cancelled"))throw new IllegalArgumentException("invalid operating-hours transition");if(to.equals("active")){jdbc.update("UPDATE operating_hours_batches SET status='superseded',lock_version=lock_version+1,updated_at=clock_timestamp(),updated_by=? WHERE organization_id=? AND target_type=? AND target_id=? AND status='active' AND id<>?",c.actorId(),c.organizationId(),type,target,id);}
  var changed=jdbc.update("UPDATE operating_hours_batches SET status=?,lock_version=lock_version+1,updated_at=clock_timestamp(),updated_by=? WHERE organization_id=? AND id=? AND lock_version=?",to,c.actorId(),c.organizationId(),id,revision);if(changed!=1)throw new IllegalArgumentException("stale operating-hours revision");return new MutationResult(id,from,to,(Instant)row.get("from"),directory(c,type,target));}
 private Instant dbNow(){return Objects.requireNonNull(jdbc.queryForObject("SELECT clock_timestamp()",Timestamp.class)).toInstant();}
}
