package com.rootopathy.careos.administration.api;
import com.rootopathy.careos.administration.application.OrganizationUnitService; import com.rootopathy.careos.administration.domain.OrganizationUnitDirectory; import com.rootopathy.careos.identity.api.AuthenticationSessionState; import com.rootopathy.careos.shared.api.*; import com.rootopathy.careos.shared.domain.AuthenticatedActor; import jakarta.servlet.http.HttpServletRequest; import jakarta.servlet.http.HttpSession; import java.time.Instant; import java.util.UUID; import org.springframework.http.*; import org.springframework.security.core.Authentication; import org.springframework.web.bind.annotation.*;
@RestController public class OrganizationUnitController {private final OrganizationUnitService service;public OrganizationUnitController(OrganizationUnitService s){service=s;}
 @GetMapping("/api/v1/organizations/{organizationId}/facilities/{facilityId}/units") ResponseEntity<OrganizationUnitDirectory> directory(@PathVariable UUID organizationId,@PathVariable UUID facilityId,Authentication authentication,HttpServletRequest request){var a=actor(authentication);return ResponseEntity.ok().cacheControl(CacheControl.noStore()).body(service.directory(new OrganizationUnitService.Read(organizationId,a.id(),CorrelationIdFilter.from(request),facilityId)));}
 @PostMapping("/api/v1/organizations/{organizationId}/facilities/{facilityId}/units") ResponseEntity<String> create(@PathVariable UUID organizationId,@PathVariable UUID facilityId,@RequestHeader(value="Idempotency-Key",required=false)String key,@RequestBody UnitCreate body,Authentication authentication,HttpServletRequest request){var a=actor(authentication);var r=service.create(new OrganizationUnitService.Create(organizationId,a.id(),CorrelationIdFilter.from(request),key,facilityId,body.parentId(),body.unitCode(),body.unitType(),body.name(),body.effectiveFrom(),body.effectiveTo(),body.reason()));return ResponseEntity.status(r.response().statusCode()).cacheControl(CacheControl.noStore()).contentType(MediaType.APPLICATION_JSON).body(r.response().bodyJson());}
 @PutMapping("/api/v1/organizations/{organizationId}/facilities/{facilityId}/units/{unitId}") ResponseEntity<String> update(@PathVariable UUID organizationId,@PathVariable UUID facilityId,@PathVariable UUID unitId,@RequestHeader(value=HttpHeaders.IF_MATCH,required=false)String etag,@RequestHeader(value="Idempotency-Key",required=false)String key,@RequestBody UnitCreate body,Authentication authentication,HttpServletRequest request){var a=actor(authentication);var r=service.update(new OrganizationUnitService.Update(organizationId,a.id(),CorrelationIdFilter.from(request),key,etag,facilityId,unitId,body.parentId(),body.unitCode(),body.unitType(),body.name(),body.effectiveFrom(),body.effectiveTo(),body.reason()));return ResponseEntity.status(r.response().statusCode()).cacheControl(CacheControl.noStore()).contentType(MediaType.APPLICATION_JSON).body(r.response().bodyJson());}
 @PostMapping("/api/v1/organizations/{organizationId}/facilities/{facilityId}/units/{unitId}/reparentings") ResponseEntity<String> reparent(@PathVariable UUID organizationId,@PathVariable UUID facilityId,@PathVariable UUID unitId,@RequestHeader(value=HttpHeaders.IF_MATCH,required=false)String etag,@RequestHeader(value="Idempotency-Key",required=false)String key,@RequestBody Reparent body,Authentication authentication,HttpServletRequest request){var a=actor(authentication);var r=service.reparent(new OrganizationUnitService.Reparent(organizationId,a.id(),CorrelationIdFilter.from(request),key,etag,facilityId,unitId,body.parentId(),body.effectiveFrom(),body.reason()));return ResponseEntity.status(r.response().statusCode()).cacheControl(CacheControl.noStore()).contentType(MediaType.APPLICATION_JSON).body(r.response().bodyJson());}
 @PostMapping("/api/v1/organizations/{organizationId}/facilities/{facilityId}/units/{unitId}/activations") ResponseEntity<String> activate(@PathVariable UUID organizationId,@PathVariable UUID facilityId,@PathVariable UUID unitId,@RequestHeader(value=HttpHeaders.IF_MATCH,required=false)String etag,@RequestHeader(value="Idempotency-Key",required=false)String key,@RequestBody Lifecycle body,Authentication authentication,HttpServletRequest request){return lifecycle(organizationId,facilityId,unitId,etag,key,body,authentication,request,"activate");}
 @PostMapping("/api/v1/organizations/{organizationId}/facilities/{facilityId}/units/{unitId}/suspensions") ResponseEntity<String> suspend(@PathVariable UUID organizationId,@PathVariable UUID facilityId,@PathVariable UUID unitId,@RequestHeader(value=HttpHeaders.IF_MATCH,required=false)String etag,@RequestHeader(value="Idempotency-Key",required=false)String key,@RequestBody Lifecycle body,Authentication authentication,HttpServletRequest request){return lifecycle(organizationId,facilityId,unitId,etag,key,body,authentication,request,"suspend");}
 @PostMapping("/api/v1/organizations/{organizationId}/facilities/{facilityId}/units/{unitId}/reactivations") ResponseEntity<String> reactivate(@PathVariable UUID organizationId,@PathVariable UUID facilityId,@PathVariable UUID unitId,@RequestHeader(value=HttpHeaders.IF_MATCH,required=false)String etag,@RequestHeader(value="Idempotency-Key",required=false)String key,@RequestBody Lifecycle body,Authentication authentication,HttpServletRequest request){return lifecycle(organizationId,facilityId,unitId,etag,key,body,authentication,request,"reactivate");}
 @PostMapping("/api/v1/organizations/{organizationId}/facilities/{facilityId}/units/{unitId}/closures") ResponseEntity<String> close(@PathVariable UUID organizationId,@PathVariable UUID facilityId,@PathVariable UUID unitId,@RequestHeader(value=HttpHeaders.IF_MATCH,required=false)String etag,@RequestHeader(value="Idempotency-Key",required=false)String key,@RequestBody Closure body,Authentication authentication,HttpServletRequest request){var a=actor(authentication);var session=request.getSession(false);var r=service.close(new OrganizationUnitService.Close(organizationId,a.id(),CorrelationIdFilter.from(request),key,etag,facilityId,unitId,body.effectiveTo(),body.reason(),assurance(session,AuthenticationSessionState.RECENT_AUTHENTICATION_AT),assurance(session,AuthenticationSessionState.MFA_AUTHENTICATED_AT)));return ResponseEntity.status(r.response().statusCode()).cacheControl(CacheControl.noStore()).contentType(MediaType.APPLICATION_JSON).body(r.response().bodyJson());}
 private ResponseEntity<String> lifecycle(UUID organizationId,UUID facilityId,UUID unitId,String etag,String key,Lifecycle body,Authentication authentication,HttpServletRequest request,String action){var a=actor(authentication);var session=request.getSession(false);var command=new OrganizationUnitService.Lifecycle(organizationId,a.id(),CorrelationIdFilter.from(request),key,etag,facilityId,unitId,body.reason(),assurance(session,AuthenticationSessionState.RECENT_AUTHENTICATION_AT),assurance(session,AuthenticationSessionState.MFA_AUTHENTICATED_AT));var r=switch(action){case "activate"->service.activate(command);case "suspend"->service.suspend(command);case "reactivate"->service.reactivate(command);default->throw new IllegalArgumentException("unsupported lifecycle action");};return ResponseEntity.status(r.response().statusCode()).cacheControl(CacheControl.noStore()).contentType(MediaType.APPLICATION_JSON).body(r.response().bodyJson());}
 private static AuthenticatedActor actor(Authentication a){if(a==null||!(a.getPrincipal() instanceof AuthenticatedActor actor))throw new ApiProblemException(HttpStatus.UNAUTHORIZED,"authentication-required","Authentication required","A valid authenticated session is required.");return actor;} public record UnitCreate(UUID parentId,String unitCode,String unitType,String name,Instant effectiveFrom,Instant effectiveTo,String reason){}
 private static Instant assurance(HttpSession session,String key){var value=session==null?null:session.getAttribute(key);return value instanceof Long epochMillis?Instant.ofEpochMilli(epochMillis):null;}
 public record Reparent(UUID parentId,Instant effectiveFrom,String reason){}
 public record Lifecycle(String reason){}
 public record Closure(Instant effectiveTo,String reason){}
}
